"""Constants."""


CONT = "CONT"
HEAD = "HEAD"
ABBR = "ABBR"
ADDR = "ADDR"
ADOP = "ADOP"
ADR1 = "ADR1"
ADR2 = "ADR2"
ADR3 = "ADR3"
AGE = "AGE"
AGNC = "AGNC"
ALIA = "ALIA"
ANCI = "ANCI"
ANUL = "ANUL"
ASSO = "ASSO"
AUTH = "AUTH"
BAPL = "BAPL"
BAPM = "BAPM"
BARM = "BARM"
BASM = "BASM"
BIRT = "BIRT"
BLES = "BLES"
BURI = "BURI"
CALN = "CALN"
CAST = "CAST"
CAUS = "CAUS"
CENS = "CENS"
CHAN = "CHAN"
CHIL = "CHIL"
CHR = "CHR"
CHRA = "CHRA"
CITY = "CITY"
CONF = "CONF"
CONL = "CONL"
COPR = "COPR"
CORP = "CORP"
CREA = "CREA"
CREM = "CREM"
CROP = "CROP"
CTRY = "CTRY"
DATA = "DATA"
DATE = "DATE"
DEAT = "DEAT"
DESI = "DESI"
DEST = "DEST"
DIV = "DIV"
DIVF = "DIVF"
DSCR = "DSCR"
EDUC = "EDUC"
EMAIL = "EMAIL"
EMIG = "EMIG"
ENDL = "ENDL"
ENGA = "ENGA"
EVEN = "EVEN"
EXID = "EXID"
FACT = "FACT"
FAM = "FAM"
FAMC = "FAMC"
FAMS = "FAMS"
FAX = "FAX"
FCOM = "FCOM"
FILE = "FILE"
FORM = "FORM"
GEDC = "GEDC"
GIVN = "GIVN"
GRAD = "GRAD"
HEIGHT = "HEIGHT"
HUSB = "HUSB"
IDNO = "IDNO"
IMMI = "IMMI"
INDI = "INDI"
INIL = "INIL"
LANG = "LANG"
LATI = "LATI"
LEFT = "LEFT"
LONG = "LONG"
MAP = "MAP"
MARB = "MARB"
MARC = "MARC"
MARL = "MARL"
MARR = "MARR"
MARS = "MARS"
MEDI = "MEDI"
MIME = "MIME"
NAME = "NAME"
NATI = "NATI"
NATU = "NATU"
NCHI = "NCHI"
NICK = "NICK"
NMR = "NMR"
NO = "NO"
NOTE = "NOTE"
NPFX = "NPFX"
NSFX = "NSFX"
OBJE = "OBJE"
OCCU = "OCCU"
ORDN = "ORDN"
PAGE = "PAGE"
PEDI = "PEDI"
PHON = "PHON"
PHRASE = "PHRASE"
PLAC = "PLAC"
POST = "POST"
PROB = "PROB"
PROP = "PROP"
PUBL = "PUBL"
QUAY = "QUAY"
REFN = "REFN"
RELI = "RELI"
REPO = "REPO"
RESI = "RESI"
RESN = "RESN"
RETI = "RETI"
ROLE = "ROLE"
SCHMA = "SCHMA"
SDATE = "SDATE"
SEX = "SEX"
SLGC = "SLGC"
SLGS = "SLGS"
SNOTE = "SNOTE"
SOUR = "SOUR"
SPFX = "SPFX"
SSN = "SSN"
STAE = "STAE"
STAT = "STAT"
SUBM = "SUBM"
SURN = "SURN"
TAG = "TAG"
TEMP = "TEMP"
TEXT = "TEXT"
TIME = "TIME"
TITL = "TITL"
TOP = "TOP"
TRAN = "TRAN"
TRLR = "TRLR"
TYPE = "TYPE"
UID = "UID"
VERS = "VERS"
WIDTH = "WIDTH"
WIFE = "WIFE"
WILL = "WILL"
WWW = "WWW"

payloads = {
    "https://gedcom.io/terms/v7/ABBR": "http://www.w3.org/2001/XMLSchema#string",
    "https://gedcom.io/terms/v7/ADDR": "http://www.w3.org/2001/XMLSchema#string",
    "https://gedcom.io/terms/v7/ADOP": "Y|<NULL>",
    "https://gedcom.io/terms/v7/FAMC-ADOP": "https://gedcom.io/terms/v7/type-Enum",
    "https://gedcom.io/terms/v7/ADR1": "http://www.w3.org/2001/XMLSchema#string",
    "https://gedcom.io/terms/v7/ADR2": "http://www.w3.org/2001/XMLSchema#string",
    "https://gedcom.io/terms/v7/ADR3": "http://www.w3.org/2001/XMLSchema#string",
    "https://gedcom.io/terms/v7/AGE": "https://gedcom.io/terms/v7/type-Age",
    "https://gedcom.io/terms/v7/AGNC": "http://www.w3.org/2001/XMLSchema#string",
    "https://gedcom.io/terms/v7/ALIA": "@<https://gedcom.io/terms/v7/record-INDI>@",
    "https://gedcom.io/terms/v7/ANCI": "@<https://gedcom.io/terms/v7/record-SUBM>@",
    "https://gedcom.io/terms/v7/ANUL": "Y|<NULL>",
    "https://gedcom.io/terms/v7/ASSO": "@<https://gedcom.io/terms/v7/record-INDI>@",
    "https://gedcom.io/terms/v7/AUTH": "http://www.w3.org/2001/XMLSchema#string",
    "https://gedcom.io/terms/v7/BAPL": "",
    "https://gedcom.io/terms/v7/BAPM": "Y|<NULL>",
    "https://gedcom.io/terms/v7/BARM": "Y|<NULL>",
    "https://gedcom.io/terms/v7/BASM": "Y|<NULL>",
    "https://gedcom.io/terms/v7/BIRT": "Y|<NULL>",
    "https://gedcom.io/terms/v7/BLES": "Y|<NULL>",
    "https://gedcom.io/terms/v7/BURI": "Y|<NULL>",
    "https://gedcom.io/terms/v7/CALN": "http://www.w3.org/2001/XMLSchema#string",
    "https://gedcom.io/terms/v7/CAST": "http://www.w3.org/2001/XMLSchema#string",
    "https://gedcom.io/terms/v7/CAUS": "http://www.w3.org/2001/XMLSchema#string",
    "https://gedcom.io/terms/v7/FAM-CENS": "Y|<NULL>",
    "https://gedcom.io/terms/v7/INDI-CENS": "Y|<NULL>",
    "https://gedcom.io/terms/v7/CHAN": "",
    "https://gedcom.io/terms/v7/CHIL": "@<https://gedcom.io/terms/v7/record-INDI>@",
    "https://gedcom.io/terms/v7/CHRA": "Y|<NULL>",
    "https://gedcom.io/terms/v7/CHR": "Y|<NULL>",
    "https://gedcom.io/terms/v7/CITY": "http://www.w3.org/2001/XMLSchema#string",
    "https://gedcom.io/terms/v7/CONF": "Y|<NULL>",
    "https://gedcom.io/terms/v7/CONL": "",
    "https://gedcom.io/terms/v7/COPR": "http://www.w3.org/2001/XMLSchema#string",
    "https://gedcom.io/terms/v7/CORP": "http://www.w3.org/2001/XMLSchema#string",
    "https://gedcom.io/terms/v7/CREA": "",
    "https://gedcom.io/terms/v7/CREM": "Y|<NULL>",
    "https://gedcom.io/terms/v7/CROP": "",
    "https://gedcom.io/terms/v7/CTRY": "http://www.w3.org/2001/XMLSchema#string",
    "https://gedcom.io/terms/v7/DATA": "",
    "https://gedcom.io/terms/v7/SOUR-DATA": "",
    "https://gedcom.io/terms/v7/HEAD-SOUR-DATA": "http://www.w3.org/2001/XMLSchema#string",
    "https://gedcom.io/terms/v7/DATE": "https://gedcom.io/terms/v7/type-Date",
    "https://gedcom.io/terms/v7/DATE-exact": "https://gedcom.io/terms/v7/type-Date#exact",
    "https://gedcom.io/terms/v7/HEAD-DATE": "https://gedcom.io/terms/v7/type-Date#exact",
    "https://gedcom.io/terms/v7/NO-DATE": "https://gedcom.io/terms/v7/type-Date#period",
    "https://gedcom.io/terms/v7/DATA-EVEN-DATE": "https://gedcom.io/terms/v7/type-Date#period",
    "https://gedcom.io/terms/v7/DEAT": "Y|<NULL>",
    "https://gedcom.io/terms/v7/DESI": "@<https://gedcom.io/terms/v7/record-SUBM>@",
    "https://gedcom.io/terms/v7/DEST": "http://www.w3.org/2001/XMLSchema#string",
    "https://gedcom.io/terms/v7/DIVF": "Y|<NULL>",
    "https://gedcom.io/terms/v7/DIV": "Y|<NULL>",
    "https://gedcom.io/terms/v7/DSCR": "http://www.w3.org/2001/XMLSchema#string",
    "https://gedcom.io/terms/v7/EDUC": "http://www.w3.org/2001/XMLSchema#string",
    "https://gedcom.io/terms/v7/EMAIL": "http://www.w3.org/2001/XMLSchema#string",
    "https://gedcom.io/terms/v7/EMIG": "Y|<NULL>",
    "https://gedcom.io/terms/v7/ENDL": "",
    "https://gedcom.io/terms/v7/ENGA": "Y|<NULL>",
    "https://gedcom.io/terms/v7/FAM-EVEN": "http://www.w3.org/2001/XMLSchema#string",
    "https://gedcom.io/terms/v7/INDI-EVEN": "http://www.w3.org/2001/XMLSchema#string",
    "https://gedcom.io/terms/v7/DATA-EVEN": "https://gedcom.io/terms/v7/type-List#Enum",
    "https://gedcom.io/terms/v7/SOUR-EVEN": "https://gedcom.io/terms/v7/type-Enum",
    "https://gedcom.io/terms/v7/EXID": "http://www.w3.org/2001/XMLSchema#string",
    "https://gedcom.io/terms/v7/record-FAM": "",
    "https://gedcom.io/terms/v7/FAM-FACT": "http://www.w3.org/2001/XMLSchema#string",
    "https://gedcom.io/terms/v7/INDI-FACT": "http://www.w3.org/2001/XMLSchema#string",
    "https://gedcom.io/terms/v7/INDI-FAMC": "@<https://gedcom.io/terms/v7/record-FAM>@",
    "https://gedcom.io/terms/v7/FAMC": "@<https://gedcom.io/terms/v7/record-FAM>@",
    "https://gedcom.io/terms/v7/ADOP-FAMC": "@<https://gedcom.io/terms/v7/record-FAM>@",
    "https://gedcom.io/terms/v7/FAMS": "@<https://gedcom.io/terms/v7/record-FAM>@",
    "https://gedcom.io/terms/v7/FAX": "http://www.w3.org/2001/XMLSchema#string",
    "https://gedcom.io/terms/v7/FCOM": "Y|<NULL>",
    "https://gedcom.io/terms/v7/FILE": "http://www.w3.org/2001/XMLSchema#string",
    "https://gedcom.io/terms/v7/FORM": "http://www.w3.org/ns/dcat#mediaType",
    "https://gedcom.io/terms/v7/PLAC-FORM": "https://gedcom.io/terms/v7/type-List#Text",
    "https://gedcom.io/terms/v7/HEAD-PLAC-FORM": "https://gedcom.io/terms/v7/type-List#Text",
    "https://gedcom.io/terms/v7/GEDC": "",
    "https://gedcom.io/terms/v7/GIVN": "http://www.w3.org/2001/XMLSchema#string",
    "https://gedcom.io/terms/v7/GRAD": "Y|<NULL>",
    "https://gedcom.io/terms/v7/HEIGHT": "http://www.w3.org/2001/XMLSchema#nonNegativeInteger",
    "https://gedcom.io/terms/v7/HUSB": "",
    "https://gedcom.io/terms/v7/FAM-HUSB": "@<https://gedcom.io/terms/v7/record-INDI>@",
    "https://gedcom.io/terms/v7/IDNO": "http://www.w3.org/2001/XMLSchema#string",
    "https://gedcom.io/terms/v7/IMMI": "Y|<NULL>",
    "https://gedcom.io/terms/v7/record-INDI": "",
    "https://gedcom.io/terms/v7/INIL": "",
    "https://gedcom.io/terms/v7/LANG": "http://www.w3.org/2001/XMLSchema#Language",
    "https://gedcom.io/terms/v7/HEAD-LANG": "http://www.w3.org/2001/XMLSchema#Language",
    "https://gedcom.io/terms/v7/SUBM-LANG": "http://www.w3.org/2001/XMLSchema#Language",
    "https://gedcom.io/terms/v7/LATI": "http://www.w3.org/2001/XMLSchema#string",
    "https://gedcom.io/terms/v7/LEFT": "http://www.w3.org/2001/XMLSchema#nonNegativeInteger",
    "https://gedcom.io/terms/v7/LONG": "http://www.w3.org/2001/XMLSchema#string",
    "https://gedcom.io/terms/v7/MAP": "",
    "https://gedcom.io/terms/v7/MARB": "Y|<NULL>",
    "https://gedcom.io/terms/v7/MARC": "Y|<NULL>",
    "https://gedcom.io/terms/v7/MARL": "Y|<NULL>",
    "https://gedcom.io/terms/v7/MARR": "Y|<NULL>",
    "https://gedcom.io/terms/v7/MARS": "Y|<NULL>",
    "https://gedcom.io/terms/v7/MEDI": "https://gedcom.io/terms/v7/type-Enum",
    "https://gedcom.io/terms/v7/MIME": "http://www.w3.org/ns/dcat#mediaType",
    "https://gedcom.io/terms/v7/NAME": "http://www.w3.org/2001/XMLSchema#string",
    "https://gedcom.io/terms/v7/INDI-NAME": "https://gedcom.io/terms/v7/type-Name",
    "https://gedcom.io/terms/v7/NATI": "http://www.w3.org/2001/XMLSchema#string",
    "https://gedcom.io/terms/v7/NATU": "Y|<NULL>",
    "https://gedcom.io/terms/v7/FAM-NCHI": "http://www.w3.org/2001/XMLSchema#nonNegativeInteger",
    "https://gedcom.io/terms/v7/INDI-NCHI": "http://www.w3.org/2001/XMLSchema#nonNegativeInteger",
    "https://gedcom.io/terms/v7/NICK": "http://www.w3.org/2001/XMLSchema#string",
    "https://gedcom.io/terms/v7/NMR": "http://www.w3.org/2001/XMLSchema#nonNegativeInteger",
    "https://gedcom.io/terms/v7/NO": "https://gedcom.io/terms/v7/type-Enum",
    "https://gedcom.io/terms/v7/NOTE": "http://www.w3.org/2001/XMLSchema#string",
    "https://gedcom.io/terms/v7/NPFX": "http://www.w3.org/2001/XMLSchema#string",
    "https://gedcom.io/terms/v7/NSFX": "http://www.w3.org/2001/XMLSchema#string",
    "https://gedcom.io/terms/v7/OBJE": "@<https://gedcom.io/terms/v7/record-OBJE>@",
    "https://gedcom.io/terms/v7/record-OBJE": "",
    "https://gedcom.io/terms/v7/OCCU": "http://www.w3.org/2001/XMLSchema#string",
    "https://gedcom.io/terms/v7/ORDN": "Y|<NULL>",
    "https://gedcom.io/terms/v7/PAGE": "http://www.w3.org/2001/XMLSchema#string",
    "https://gedcom.io/terms/v7/PEDI": "https://gedcom.io/terms/v7/type-Enum",
    "https://gedcom.io/terms/v7/PHON": "http://www.w3.org/2001/XMLSchema#string",
    "https://gedcom.io/terms/v7/PHRASE": "http://www.w3.org/2001/XMLSchema#string",
    "https://gedcom.io/terms/v7/PLAC": "https://gedcom.io/terms/v7/type-List#Text",
    "https://gedcom.io/terms/v7/HEAD-PLAC": "",
    "https://gedcom.io/terms/v7/POST": "http://www.w3.org/2001/XMLSchema#string",
    "https://gedcom.io/terms/v7/PROB": "Y|<NULL>",
    "https://gedcom.io/terms/v7/PROP": "http://www.w3.org/2001/XMLSchema#string",
    "https://gedcom.io/terms/v7/PUBL": "http://www.w3.org/2001/XMLSchema#string",
    "https://gedcom.io/terms/v7/QUAY": "https://gedcom.io/terms/v7/type-Enum",
    "https://gedcom.io/terms/v7/REFN": "http://www.w3.org/2001/XMLSchema#string",
    "https://gedcom.io/terms/v7/RELI": "http://www.w3.org/2001/XMLSchema#string",
    "https://gedcom.io/terms/v7/INDI-RELI": "http://www.w3.org/2001/XMLSchema#string",
    "https://gedcom.io/terms/v7/RESN": "https://gedcom.io/terms/v7/type-List#Enum",
    "https://gedcom.io/terms/v7/REPO": "@<https://gedcom.io/terms/v7/record-REPO>@",
    "https://gedcom.io/terms/v7/record-REPO": "",
    "https://gedcom.io/terms/v7/FAM-RESI": "http://www.w3.org/2001/XMLSchema#string",
    "https://gedcom.io/terms/v7/INDI-RESI": "http://www.w3.org/2001/XMLSchema#string",
    "https://gedcom.io/terms/v7/RETI": "Y|<NULL>",
    "https://gedcom.io/terms/v7/ROLE": "https://gedcom.io/terms/v7/type-Enum",
    "https://gedcom.io/terms/v7/SCHMA": "",
    "https://gedcom.io/terms/v7/SDATE": "https://gedcom.io/terms/v7/type-Date",
    "https://gedcom.io/terms/v7/SEX": "https://gedcom.io/terms/v7/type-Enum",
    "https://gedcom.io/terms/v7/SLGC": "",
    "https://gedcom.io/terms/v7/SLGS": "",
    "https://gedcom.io/terms/v7/SNOTE": "@<https://gedcom.io/terms/v7/record-SNOTE>@",
    "https://gedcom.io/terms/v7/record-SNOTE": "http://www.w3.org/2001/XMLSchema#string",
    "https://gedcom.io/terms/v7/SOUR": "@<https://gedcom.io/terms/v7/record-SOUR>@",
    "https://gedcom.io/terms/v7/record-SOUR": "",
    "https://gedcom.io/terms/v7/HEAD-SOUR": "http://www.w3.org/2001/XMLSchema#string",
    "https://gedcom.io/terms/v7/SPFX": "http://www.w3.org/2001/XMLSchema#string",
    "https://gedcom.io/terms/v7/SSN": "http://www.w3.org/2001/XMLSchema#string",
    "https://gedcom.io/terms/v7/STAE": "http://www.w3.org/2001/XMLSchema#string",
    "https://gedcom.io/terms/v7/ord-STAT": "https://gedcom.io/terms/v7/type-Enum",
    "https://gedcom.io/terms/v7/FAMC-STAT": "https://gedcom.io/terms/v7/type-Enum",
    "https://gedcom.io/terms/v7/SUBM": "@<https://gedcom.io/terms/v7/record-SUBM>@",
    "https://gedcom.io/terms/v7/record-SUBM": "",
    "https://gedcom.io/terms/v7/SURN": "http://www.w3.org/2001/XMLSchema#string",
    "https://gedcom.io/terms/v7/TAG": "http://www.w3.org/2001/XMLSchema#string",
    "https://gedcom.io/terms/v7/TEMP": "http://www.w3.org/2001/XMLSchema#string",
    "https://gedcom.io/terms/v7/TEXT": "http://www.w3.org/2001/XMLSchema#string",
    "https://gedcom.io/terms/v7/TIME": "https://gedcom.io/terms/v7/type-Time",
    "https://gedcom.io/terms/v7/TITL": "http://www.w3.org/2001/XMLSchema#string",
    "https://gedcom.io/terms/v7/INDI-TITL": "http://www.w3.org/2001/XMLSchema#string",
    "https://gedcom.io/terms/v7/TOP": "http://www.w3.org/2001/XMLSchema#nonNegativeInteger",
    "https://gedcom.io/terms/v7/NAME-TRAN": "https://gedcom.io/terms/v7/type-Name",
    "https://gedcom.io/terms/v7/PLAC-TRAN": "https://gedcom.io/terms/v7/type-List#Text",
    "https://gedcom.io/terms/v7/NOTE-TRAN": "http://www.w3.org/2001/XMLSchema#string",
    "https://gedcom.io/terms/v7/FILE-TRAN": "http://www.w3.org/2001/XMLSchema#string",
    "https://gedcom.io/terms/v7/TYPE": "http://www.w3.org/2001/XMLSchema#string",
    "https://gedcom.io/terms/v7/NAME-TYPE": "https://gedcom.io/terms/v7/type-Enum",
    "https://gedcom.io/terms/v7/EXID-TYPE": "http://www.w3.org/2001/XMLSchema#string",
    "https://gedcom.io/terms/v7/UID": "http://www.w3.org/2001/XMLSchema#string",
    "https://gedcom.io/terms/v7/VERS": "http://www.w3.org/2001/XMLSchema#string",
    "https://gedcom.io/terms/v7/GEDC-VERS": "http://www.w3.org/2001/XMLSchema#string",
    "https://gedcom.io/terms/v7/WIDTH": "http://www.w3.org/2001/XMLSchema#nonNegativeInteger",
    "https://gedcom.io/terms/v7/WIFE": "",
    "https://gedcom.io/terms/v7/FAM-WIFE": "@<https://gedcom.io/terms/v7/record-INDI>@",
    "https://gedcom.io/terms/v7/WILL": "Y|<NULL>",
    "https://gedcom.io/terms/v7/WWW": "http://www.w3.org/2001/XMLSchema#string",
}

substructures = {
    "https://gedcom.io/terms/v7/record-SOUR": {
        "ABBR": "https://gedcom.io/terms/v7/ABBR",
        "AUTH": "https://gedcom.io/terms/v7/AUTH",
        "CHAN": "https://gedcom.io/terms/v7/CHAN",
        "CREA": "https://gedcom.io/terms/v7/CREA",
        "DATA": "https://gedcom.io/terms/v7/DATA",
        "EXID": "https://gedcom.io/terms/v7/EXID",
        "NOTE": "https://gedcom.io/terms/v7/NOTE",
        "OBJE": "https://gedcom.io/terms/v7/OBJE",
        "PUBL": "https://gedcom.io/terms/v7/PUBL",
        "REFN": "https://gedcom.io/terms/v7/REFN",
        "REPO": "https://gedcom.io/terms/v7/REPO",
        "SNOTE": "https://gedcom.io/terms/v7/SNOTE",
        "TEXT": "https://gedcom.io/terms/v7/TEXT",
        "TITL": "https://gedcom.io/terms/v7/TITL",
        "UID": "https://gedcom.io/terms/v7/UID",
    },
    "https://gedcom.io/terms/v7/ADOP": {
        "ADDR": "https://gedcom.io/terms/v7/ADDR",
        "AGE": "https://gedcom.io/terms/v7/AGE",
        "AGNC": "https://gedcom.io/terms/v7/AGNC",
        "ASSO": "https://gedcom.io/terms/v7/ASSO",
        "CAUS": "https://gedcom.io/terms/v7/CAUS",
        "DATE": "https://gedcom.io/terms/v7/DATE",
        "EMAIL": "https://gedcom.io/terms/v7/EMAIL",
        "FAMC": "https://gedcom.io/terms/v7/ADOP-FAMC",
        "FAX": "https://gedcom.io/terms/v7/FAX",
        "NOTE": "https://gedcom.io/terms/v7/NOTE",
        "OBJE": "https://gedcom.io/terms/v7/OBJE",
        "PHON": "https://gedcom.io/terms/v7/PHON",
        "PLAC": "https://gedcom.io/terms/v7/PLAC",
        "RELI": "https://gedcom.io/terms/v7/RELI",
        "RESN": "https://gedcom.io/terms/v7/RESN",
        "SDATE": "https://gedcom.io/terms/v7/SDATE",
        "SNOTE": "https://gedcom.io/terms/v7/SNOTE",
        "SOUR": "https://gedcom.io/terms/v7/SOUR",
        "TYPE": "https://gedcom.io/terms/v7/TYPE",
        "UID": "https://gedcom.io/terms/v7/UID",
        "WWW": "https://gedcom.io/terms/v7/WWW",
    },
    "https://gedcom.io/terms/v7/ANUL": {
        "ADDR": "https://gedcom.io/terms/v7/ADDR",
        "AGNC": "https://gedcom.io/terms/v7/AGNC",
        "ASSO": "https://gedcom.io/terms/v7/ASSO",
        "CAUS": "https://gedcom.io/terms/v7/CAUS",
        "DATE": "https://gedcom.io/terms/v7/DATE",
        "EMAIL": "https://gedcom.io/terms/v7/EMAIL",
        "FAX": "https://gedcom.io/terms/v7/FAX",
        "HUSB": "https://gedcom.io/terms/v7/HUSB",
        "NOTE": "https://gedcom.io/terms/v7/NOTE",
        "OBJE": "https://gedcom.io/terms/v7/OBJE",
        "PHON": "https://gedcom.io/terms/v7/PHON",
        "PLAC": "https://gedcom.io/terms/v7/PLAC",
        "RELI": "https://gedcom.io/terms/v7/RELI",
        "RESN": "https://gedcom.io/terms/v7/RESN",
        "SDATE": "https://gedcom.io/terms/v7/SDATE",
        "SNOTE": "https://gedcom.io/terms/v7/SNOTE",
        "SOUR": "https://gedcom.io/terms/v7/SOUR",
        "TYPE": "https://gedcom.io/terms/v7/TYPE",
        "UID": "https://gedcom.io/terms/v7/UID",
        "WIFE": "https://gedcom.io/terms/v7/WIFE",
        "WWW": "https://gedcom.io/terms/v7/WWW",
    },
    "https://gedcom.io/terms/v7/BAPM": {
        "ADDR": "https://gedcom.io/terms/v7/ADDR",
        "AGE": "https://gedcom.io/terms/v7/AGE",
        "AGNC": "https://gedcom.io/terms/v7/AGNC",
        "ASSO": "https://gedcom.io/terms/v7/ASSO",
        "CAUS": "https://gedcom.io/terms/v7/CAUS",
        "DATE": "https://gedcom.io/terms/v7/DATE",
        "EMAIL": "https://gedcom.io/terms/v7/EMAIL",
        "FAX": "https://gedcom.io/terms/v7/FAX",
        "NOTE": "https://gedcom.io/terms/v7/NOTE",
        "OBJE": "https://gedcom.io/terms/v7/OBJE",
        "PHON": "https://gedcom.io/terms/v7/PHON",
        "PLAC": "https://gedcom.io/terms/v7/PLAC",
        "RELI": "https://gedcom.io/terms/v7/RELI",
        "RESN": "https://gedcom.io/terms/v7/RESN",
        "SDATE": "https://gedcom.io/terms/v7/SDATE",
        "SNOTE": "https://gedcom.io/terms/v7/SNOTE",
        "SOUR": "https://gedcom.io/terms/v7/SOUR",
        "TYPE": "https://gedcom.io/terms/v7/TYPE",
        "UID": "https://gedcom.io/terms/v7/UID",
        "WWW": "https://gedcom.io/terms/v7/WWW",
    },
    "https://gedcom.io/terms/v7/BARM": {
        "ADDR": "https://gedcom.io/terms/v7/ADDR",
        "AGE": "https://gedcom.io/terms/v7/AGE",
        "AGNC": "https://gedcom.io/terms/v7/AGNC",
        "ASSO": "https://gedcom.io/terms/v7/ASSO",
        "CAUS": "https://gedcom.io/terms/v7/CAUS",
        "DATE": "https://gedcom.io/terms/v7/DATE",
        "EMAIL": "https://gedcom.io/terms/v7/EMAIL",
        "FAX": "https://gedcom.io/terms/v7/FAX",
        "NOTE": "https://gedcom.io/terms/v7/NOTE",
        "OBJE": "https://gedcom.io/terms/v7/OBJE",
        "PHON": "https://gedcom.io/terms/v7/PHON",
        "PLAC": "https://gedcom.io/terms/v7/PLAC",
        "RELI": "https://gedcom.io/terms/v7/RELI",
        "RESN": "https://gedcom.io/terms/v7/RESN",
        "SDATE": "https://gedcom.io/terms/v7/SDATE",
        "SNOTE": "https://gedcom.io/terms/v7/SNOTE",
        "SOUR": "https://gedcom.io/terms/v7/SOUR",
        "TYPE": "https://gedcom.io/terms/v7/TYPE",
        "UID": "https://gedcom.io/terms/v7/UID",
        "WWW": "https://gedcom.io/terms/v7/WWW",
    },
    "https://gedcom.io/terms/v7/BASM": {
        "ADDR": "https://gedcom.io/terms/v7/ADDR",
        "AGE": "https://gedcom.io/terms/v7/AGE",
        "AGNC": "https://gedcom.io/terms/v7/AGNC",
        "ASSO": "https://gedcom.io/terms/v7/ASSO",
        "CAUS": "https://gedcom.io/terms/v7/CAUS",
        "DATE": "https://gedcom.io/terms/v7/DATE",
        "EMAIL": "https://gedcom.io/terms/v7/EMAIL",
        "FAX": "https://gedcom.io/terms/v7/FAX",
        "NOTE": "https://gedcom.io/terms/v7/NOTE",
        "OBJE": "https://gedcom.io/terms/v7/OBJE",
        "PHON": "https://gedcom.io/terms/v7/PHON",
        "PLAC": "https://gedcom.io/terms/v7/PLAC",
        "RELI": "https://gedcom.io/terms/v7/RELI",
        "RESN": "https://gedcom.io/terms/v7/RESN",
        "SDATE": "https://gedcom.io/terms/v7/SDATE",
        "SNOTE": "https://gedcom.io/terms/v7/SNOTE",
        "SOUR": "https://gedcom.io/terms/v7/SOUR",
        "TYPE": "https://gedcom.io/terms/v7/TYPE",
        "UID": "https://gedcom.io/terms/v7/UID",
        "WWW": "https://gedcom.io/terms/v7/WWW",
    },
    "https://gedcom.io/terms/v7/BIRT": {
        "ADDR": "https://gedcom.io/terms/v7/ADDR",
        "AGE": "https://gedcom.io/terms/v7/AGE",
        "AGNC": "https://gedcom.io/terms/v7/AGNC",
        "ASSO": "https://gedcom.io/terms/v7/ASSO",
        "CAUS": "https://gedcom.io/terms/v7/CAUS",
        "DATE": "https://gedcom.io/terms/v7/DATE",
        "EMAIL": "https://gedcom.io/terms/v7/EMAIL",
        "FAMC": "https://gedcom.io/terms/v7/FAMC",
        "FAX": "https://gedcom.io/terms/v7/FAX",
        "NOTE": "https://gedcom.io/terms/v7/NOTE",
        "OBJE": "https://gedcom.io/terms/v7/OBJE",
        "PHON": "https://gedcom.io/terms/v7/PHON",
        "PLAC": "https://gedcom.io/terms/v7/PLAC",
        "RELI": "https://gedcom.io/terms/v7/RELI",
        "RESN": "https://gedcom.io/terms/v7/RESN",
        "SDATE": "https://gedcom.io/terms/v7/SDATE",
        "SNOTE": "https://gedcom.io/terms/v7/SNOTE",
        "SOUR": "https://gedcom.io/terms/v7/SOUR",
        "TYPE": "https://gedcom.io/terms/v7/TYPE",
        "UID": "https://gedcom.io/terms/v7/UID",
        "WWW": "https://gedcom.io/terms/v7/WWW",
    },
    "https://gedcom.io/terms/v7/BLES": {
        "ADDR": "https://gedcom.io/terms/v7/ADDR",
        "AGE": "https://gedcom.io/terms/v7/AGE",
        "AGNC": "https://gedcom.io/terms/v7/AGNC",
        "ASSO": "https://gedcom.io/terms/v7/ASSO",
        "CAUS": "https://gedcom.io/terms/v7/CAUS",
        "DATE": "https://gedcom.io/terms/v7/DATE",
        "EMAIL": "https://gedcom.io/terms/v7/EMAIL",
        "FAX": "https://gedcom.io/terms/v7/FAX",
        "NOTE": "https://gedcom.io/terms/v7/NOTE",
        "OBJE": "https://gedcom.io/terms/v7/OBJE",
        "PHON": "https://gedcom.io/terms/v7/PHON",
        "PLAC": "https://gedcom.io/terms/v7/PLAC",
        "RELI": "https://gedcom.io/terms/v7/RELI",
        "RESN": "https://gedcom.io/terms/v7/RESN",
        "SDATE": "https://gedcom.io/terms/v7/SDATE",
        "SNOTE": "https://gedcom.io/terms/v7/SNOTE",
        "SOUR": "https://gedcom.io/terms/v7/SOUR",
        "TYPE": "https://gedcom.io/terms/v7/TYPE",
        "UID": "https://gedcom.io/terms/v7/UID",
        "WWW": "https://gedcom.io/terms/v7/WWW",
    },
    "https://gedcom.io/terms/v7/BURI": {
        "ADDR": "https://gedcom.io/terms/v7/ADDR",
        "AGE": "https://gedcom.io/terms/v7/AGE",
        "AGNC": "https://gedcom.io/terms/v7/AGNC",
        "ASSO": "https://gedcom.io/terms/v7/ASSO",
        "CAUS": "https://gedcom.io/terms/v7/CAUS",
        "DATE": "https://gedcom.io/terms/v7/DATE",
        "EMAIL": "https://gedcom.io/terms/v7/EMAIL",
        "FAX": "https://gedcom.io/terms/v7/FAX",
        "NOTE": "https://gedcom.io/terms/v7/NOTE",
        "OBJE": "https://gedcom.io/terms/v7/OBJE",
        "PHON": "https://gedcom.io/terms/v7/PHON",
        "PLAC": "https://gedcom.io/terms/v7/PLAC",
        "RELI": "https://gedcom.io/terms/v7/RELI",
        "RESN": "https://gedcom.io/terms/v7/RESN",
        "SDATE": "https://gedcom.io/terms/v7/SDATE",
        "SNOTE": "https://gedcom.io/terms/v7/SNOTE",
        "SOUR": "https://gedcom.io/terms/v7/SOUR",
        "TYPE": "https://gedcom.io/terms/v7/TYPE",
        "UID": "https://gedcom.io/terms/v7/UID",
        "WWW": "https://gedcom.io/terms/v7/WWW",
    },
    "https://gedcom.io/terms/v7/CAST": {
        "ADDR": "https://gedcom.io/terms/v7/ADDR",
        "AGE": "https://gedcom.io/terms/v7/AGE",
        "AGNC": "https://gedcom.io/terms/v7/AGNC",
        "ASSO": "https://gedcom.io/terms/v7/ASSO",
        "CAUS": "https://gedcom.io/terms/v7/CAUS",
        "DATE": "https://gedcom.io/terms/v7/DATE",
        "EMAIL": "https://gedcom.io/terms/v7/EMAIL",
        "FAX": "https://gedcom.io/terms/v7/FAX",
        "NOTE": "https://gedcom.io/terms/v7/NOTE",
        "OBJE": "https://gedcom.io/terms/v7/OBJE",
        "PHON": "https://gedcom.io/terms/v7/PHON",
        "PLAC": "https://gedcom.io/terms/v7/PLAC",
        "RELI": "https://gedcom.io/terms/v7/RELI",
        "RESN": "https://gedcom.io/terms/v7/RESN",
        "SDATE": "https://gedcom.io/terms/v7/SDATE",
        "SNOTE": "https://gedcom.io/terms/v7/SNOTE",
        "SOUR": "https://gedcom.io/terms/v7/SOUR",
        "TYPE": "https://gedcom.io/terms/v7/TYPE",
        "UID": "https://gedcom.io/terms/v7/UID",
        "WWW": "https://gedcom.io/terms/v7/WWW",
    },
    "https://gedcom.io/terms/v7/CHR": {
        "ADDR": "https://gedcom.io/terms/v7/ADDR",
        "AGE": "https://gedcom.io/terms/v7/AGE",
        "AGNC": "https://gedcom.io/terms/v7/AGNC",
        "ASSO": "https://gedcom.io/terms/v7/ASSO",
        "CAUS": "https://gedcom.io/terms/v7/CAUS",
        "DATE": "https://gedcom.io/terms/v7/DATE",
        "EMAIL": "https://gedcom.io/terms/v7/EMAIL",
        "FAMC": "https://gedcom.io/terms/v7/FAMC",
        "FAX": "https://gedcom.io/terms/v7/FAX",
        "NOTE": "https://gedcom.io/terms/v7/NOTE",
        "OBJE": "https://gedcom.io/terms/v7/OBJE",
        "PHON": "https://gedcom.io/terms/v7/PHON",
        "PLAC": "https://gedcom.io/terms/v7/PLAC",
        "RELI": "https://gedcom.io/terms/v7/RELI",
        "RESN": "https://gedcom.io/terms/v7/RESN",
        "SDATE": "https://gedcom.io/terms/v7/SDATE",
        "SNOTE": "https://gedcom.io/terms/v7/SNOTE",
        "SOUR": "https://gedcom.io/terms/v7/SOUR",
        "TYPE": "https://gedcom.io/terms/v7/TYPE",
        "UID": "https://gedcom.io/terms/v7/UID",
        "WWW": "https://gedcom.io/terms/v7/WWW",
    },
    "https://gedcom.io/terms/v7/CHRA": {
        "ADDR": "https://gedcom.io/terms/v7/ADDR",
        "AGE": "https://gedcom.io/terms/v7/AGE",
        "AGNC": "https://gedcom.io/terms/v7/AGNC",
        "ASSO": "https://gedcom.io/terms/v7/ASSO",
        "CAUS": "https://gedcom.io/terms/v7/CAUS",
        "DATE": "https://gedcom.io/terms/v7/DATE",
        "EMAIL": "https://gedcom.io/terms/v7/EMAIL",
        "FAX": "https://gedcom.io/terms/v7/FAX",
        "NOTE": "https://gedcom.io/terms/v7/NOTE",
        "OBJE": "https://gedcom.io/terms/v7/OBJE",
        "PHON": "https://gedcom.io/terms/v7/PHON",
        "PLAC": "https://gedcom.io/terms/v7/PLAC",
        "RELI": "https://gedcom.io/terms/v7/RELI",
        "RESN": "https://gedcom.io/terms/v7/RESN",
        "SDATE": "https://gedcom.io/terms/v7/SDATE",
        "SNOTE": "https://gedcom.io/terms/v7/SNOTE",
        "SOUR": "https://gedcom.io/terms/v7/SOUR",
        "TYPE": "https://gedcom.io/terms/v7/TYPE",
        "UID": "https://gedcom.io/terms/v7/UID",
        "WWW": "https://gedcom.io/terms/v7/WWW",
    },
    "https://gedcom.io/terms/v7/CONF": {
        "ADDR": "https://gedcom.io/terms/v7/ADDR",
        "AGE": "https://gedcom.io/terms/v7/AGE",
        "AGNC": "https://gedcom.io/terms/v7/AGNC",
        "ASSO": "https://gedcom.io/terms/v7/ASSO",
        "CAUS": "https://gedcom.io/terms/v7/CAUS",
        "DATE": "https://gedcom.io/terms/v7/DATE",
        "EMAIL": "https://gedcom.io/terms/v7/EMAIL",
        "FAX": "https://gedcom.io/terms/v7/FAX",
        "NOTE": "https://gedcom.io/terms/v7/NOTE",
        "OBJE": "https://gedcom.io/terms/v7/OBJE",
        "PHON": "https://gedcom.io/terms/v7/PHON",
        "PLAC": "https://gedcom.io/terms/v7/PLAC",
        "RELI": "https://gedcom.io/terms/v7/RELI",
        "RESN": "https://gedcom.io/terms/v7/RESN",
        "SDATE": "https://gedcom.io/terms/v7/SDATE",
        "SNOTE": "https://gedcom.io/terms/v7/SNOTE",
        "SOUR": "https://gedcom.io/terms/v7/SOUR",
        "TYPE": "https://gedcom.io/terms/v7/TYPE",
        "UID": "https://gedcom.io/terms/v7/UID",
        "WWW": "https://gedcom.io/terms/v7/WWW",
    },
    "https://gedcom.io/terms/v7/CORP": {
        "ADDR": "https://gedcom.io/terms/v7/ADDR",
        "EMAIL": "https://gedcom.io/terms/v7/EMAIL",
        "FAX": "https://gedcom.io/terms/v7/FAX",
        "PHON": "https://gedcom.io/terms/v7/PHON",
        "WWW": "https://gedcom.io/terms/v7/WWW",
    },
    "https://gedcom.io/terms/v7/CREM": {
        "ADDR": "https://gedcom.io/terms/v7/ADDR",
        "AGE": "https://gedcom.io/terms/v7/AGE",
        "AGNC": "https://gedcom.io/terms/v7/AGNC",
        "ASSO": "https://gedcom.io/terms/v7/ASSO",
        "CAUS": "https://gedcom.io/terms/v7/CAUS",
        "DATE": "https://gedcom.io/terms/v7/DATE",
        "EMAIL": "https://gedcom.io/terms/v7/EMAIL",
        "FAX": "https://gedcom.io/terms/v7/FAX",
        "NOTE": "https://gedcom.io/terms/v7/NOTE",
        "OBJE": "https://gedcom.io/terms/v7/OBJE",
        "PHON": "https://gedcom.io/terms/v7/PHON",
        "PLAC": "https://gedcom.io/terms/v7/PLAC",
        "RELI": "https://gedcom.io/terms/v7/RELI",
        "RESN": "https://gedcom.io/terms/v7/RESN",
        "SDATE": "https://gedcom.io/terms/v7/SDATE",
        "SNOTE": "https://gedcom.io/terms/v7/SNOTE",
        "SOUR": "https://gedcom.io/terms/v7/SOUR",
        "TYPE": "https://gedcom.io/terms/v7/TYPE",
        "UID": "https://gedcom.io/terms/v7/UID",
        "WWW": "https://gedcom.io/terms/v7/WWW",
    },
    "https://gedcom.io/terms/v7/DEAT": {
        "ADDR": "https://gedcom.io/terms/v7/ADDR",
        "AGE": "https://gedcom.io/terms/v7/AGE",
        "AGNC": "https://gedcom.io/terms/v7/AGNC",
        "ASSO": "https://gedcom.io/terms/v7/ASSO",
        "CAUS": "https://gedcom.io/terms/v7/CAUS",
        "DATE": "https://gedcom.io/terms/v7/DATE",
        "EMAIL": "https://gedcom.io/terms/v7/EMAIL",
        "FAX": "https://gedcom.io/terms/v7/FAX",
        "NOTE": "https://gedcom.io/terms/v7/NOTE",
        "OBJE": "https://gedcom.io/terms/v7/OBJE",
        "PHON": "https://gedcom.io/terms/v7/PHON",
        "PLAC": "https://gedcom.io/terms/v7/PLAC",
        "RELI": "https://gedcom.io/terms/v7/RELI",
        "RESN": "https://gedcom.io/terms/v7/RESN",
        "SDATE": "https://gedcom.io/terms/v7/SDATE",
        "SNOTE": "https://gedcom.io/terms/v7/SNOTE",
        "SOUR": "https://gedcom.io/terms/v7/SOUR",
        "TYPE": "https://gedcom.io/terms/v7/TYPE",
        "UID": "https://gedcom.io/terms/v7/UID",
        "WWW": "https://gedcom.io/terms/v7/WWW",
    },
    "https://gedcom.io/terms/v7/DIV": {
        "ADDR": "https://gedcom.io/terms/v7/ADDR",
        "AGNC": "https://gedcom.io/terms/v7/AGNC",
        "ASSO": "https://gedcom.io/terms/v7/ASSO",
        "CAUS": "https://gedcom.io/terms/v7/CAUS",
        "DATE": "https://gedcom.io/terms/v7/DATE",
        "EMAIL": "https://gedcom.io/terms/v7/EMAIL",
        "FAX": "https://gedcom.io/terms/v7/FAX",
        "HUSB": "https://gedcom.io/terms/v7/HUSB",
        "NOTE": "https://gedcom.io/terms/v7/NOTE",
        "OBJE": "https://gedcom.io/terms/v7/OBJE",
        "PHON": "https://gedcom.io/terms/v7/PHON",
        "PLAC": "https://gedcom.io/terms/v7/PLAC",
        "RELI": "https://gedcom.io/terms/v7/RELI",
        "RESN": "https://gedcom.io/terms/v7/RESN",
        "SDATE": "https://gedcom.io/terms/v7/SDATE",
        "SNOTE": "https://gedcom.io/terms/v7/SNOTE",
        "SOUR": "https://gedcom.io/terms/v7/SOUR",
        "TYPE": "https://gedcom.io/terms/v7/TYPE",
        "UID": "https://gedcom.io/terms/v7/UID",
        "WIFE": "https://gedcom.io/terms/v7/WIFE",
        "WWW": "https://gedcom.io/terms/v7/WWW",
    },
    "https://gedcom.io/terms/v7/DIVF": {
        "ADDR": "https://gedcom.io/terms/v7/ADDR",
        "AGNC": "https://gedcom.io/terms/v7/AGNC",
        "ASSO": "https://gedcom.io/terms/v7/ASSO",
        "CAUS": "https://gedcom.io/terms/v7/CAUS",
        "DATE": "https://gedcom.io/terms/v7/DATE",
        "EMAIL": "https://gedcom.io/terms/v7/EMAIL",
        "FAX": "https://gedcom.io/terms/v7/FAX",
        "HUSB": "https://gedcom.io/terms/v7/HUSB",
        "NOTE": "https://gedcom.io/terms/v7/NOTE",
        "OBJE": "https://gedcom.io/terms/v7/OBJE",
        "PHON": "https://gedcom.io/terms/v7/PHON",
        "PLAC": "https://gedcom.io/terms/v7/PLAC",
        "RELI": "https://gedcom.io/terms/v7/RELI",
        "RESN": "https://gedcom.io/terms/v7/RESN",
        "SDATE": "https://gedcom.io/terms/v7/SDATE",
        "SNOTE": "https://gedcom.io/terms/v7/SNOTE",
        "SOUR": "https://gedcom.io/terms/v7/SOUR",
        "TYPE": "https://gedcom.io/terms/v7/TYPE",
        "UID": "https://gedcom.io/terms/v7/UID",
        "WIFE": "https://gedcom.io/terms/v7/WIFE",
        "WWW": "https://gedcom.io/terms/v7/WWW",
    },
    "https://gedcom.io/terms/v7/DSCR": {
        "ADDR": "https://gedcom.io/terms/v7/ADDR",
        "AGE": "https://gedcom.io/terms/v7/AGE",
        "AGNC": "https://gedcom.io/terms/v7/AGNC",
        "ASSO": "https://gedcom.io/terms/v7/ASSO",
        "CAUS": "https://gedcom.io/terms/v7/CAUS",
        "DATE": "https://gedcom.io/terms/v7/DATE",
        "EMAIL": "https://gedcom.io/terms/v7/EMAIL",
        "FAX": "https://gedcom.io/terms/v7/FAX",
        "NOTE": "https://gedcom.io/terms/v7/NOTE",
        "OBJE": "https://gedcom.io/terms/v7/OBJE",
        "PHON": "https://gedcom.io/terms/v7/PHON",
        "PLAC": "https://gedcom.io/terms/v7/PLAC",
        "RELI": "https://gedcom.io/terms/v7/RELI",
        "RESN": "https://gedcom.io/terms/v7/RESN",
        "SDATE": "https://gedcom.io/terms/v7/SDATE",
        "SNOTE": "https://gedcom.io/terms/v7/SNOTE",
        "SOUR": "https://gedcom.io/terms/v7/SOUR",
        "TYPE": "https://gedcom.io/terms/v7/TYPE",
        "UID": "https://gedcom.io/terms/v7/UID",
        "WWW": "https://gedcom.io/terms/v7/WWW",
    },
    "https://gedcom.io/terms/v7/EDUC": {
        "ADDR": "https://gedcom.io/terms/v7/ADDR",
        "AGE": "https://gedcom.io/terms/v7/AGE",
        "AGNC": "https://gedcom.io/terms/v7/AGNC",
        "ASSO": "https://gedcom.io/terms/v7/ASSO",
        "CAUS": "https://gedcom.io/terms/v7/CAUS",
        "DATE": "https://gedcom.io/terms/v7/DATE",
        "EMAIL": "https://gedcom.io/terms/v7/EMAIL",
        "FAX": "https://gedcom.io/terms/v7/FAX",
        "NOTE": "https://gedcom.io/terms/v7/NOTE",
        "OBJE": "https://gedcom.io/terms/v7/OBJE",
        "PHON": "https://gedcom.io/terms/v7/PHON",
        "PLAC": "https://gedcom.io/terms/v7/PLAC",
        "RELI": "https://gedcom.io/terms/v7/RELI",
        "RESN": "https://gedcom.io/terms/v7/RESN",
        "SDATE": "https://gedcom.io/terms/v7/SDATE",
        "SNOTE": "https://gedcom.io/terms/v7/SNOTE",
        "SOUR": "https://gedcom.io/terms/v7/SOUR",
        "TYPE": "https://gedcom.io/terms/v7/TYPE",
        "UID": "https://gedcom.io/terms/v7/UID",
        "WWW": "https://gedcom.io/terms/v7/WWW",
    },
    "https://gedcom.io/terms/v7/EMIG": {
        "ADDR": "https://gedcom.io/terms/v7/ADDR",
        "AGE": "https://gedcom.io/terms/v7/AGE",
        "AGNC": "https://gedcom.io/terms/v7/AGNC",
        "ASSO": "https://gedcom.io/terms/v7/ASSO",
        "CAUS": "https://gedcom.io/terms/v7/CAUS",
        "DATE": "https://gedcom.io/terms/v7/DATE",
        "EMAIL": "https://gedcom.io/terms/v7/EMAIL",
        "FAX": "https://gedcom.io/terms/v7/FAX",
        "NOTE": "https://gedcom.io/terms/v7/NOTE",
        "OBJE": "https://gedcom.io/terms/v7/OBJE",
        "PHON": "https://gedcom.io/terms/v7/PHON",
        "PLAC": "https://gedcom.io/terms/v7/PLAC",
        "RELI": "https://gedcom.io/terms/v7/RELI",
        "RESN": "https://gedcom.io/terms/v7/RESN",
        "SDATE": "https://gedcom.io/terms/v7/SDATE",
        "SNOTE": "https://gedcom.io/terms/v7/SNOTE",
        "SOUR": "https://gedcom.io/terms/v7/SOUR",
        "TYPE": "https://gedcom.io/terms/v7/TYPE",
        "UID": "https://gedcom.io/terms/v7/UID",
        "WWW": "https://gedcom.io/terms/v7/WWW",
    },
    "https://gedcom.io/terms/v7/ENGA": {
        "ADDR": "https://gedcom.io/terms/v7/ADDR",
        "AGNC": "https://gedcom.io/terms/v7/AGNC",
        "ASSO": "https://gedcom.io/terms/v7/ASSO",
        "CAUS": "https://gedcom.io/terms/v7/CAUS",
        "DATE": "https://gedcom.io/terms/v7/DATE",
        "EMAIL": "https://gedcom.io/terms/v7/EMAIL",
        "FAX": "https://gedcom.io/terms/v7/FAX",
        "HUSB": "https://gedcom.io/terms/v7/HUSB",
        "NOTE": "https://gedcom.io/terms/v7/NOTE",
        "OBJE": "https://gedcom.io/terms/v7/OBJE",
        "PHON": "https://gedcom.io/terms/v7/PHON",
        "PLAC": "https://gedcom.io/terms/v7/PLAC",
        "RELI": "https://gedcom.io/terms/v7/RELI",
        "RESN": "https://gedcom.io/terms/v7/RESN",
        "SDATE": "https://gedcom.io/terms/v7/SDATE",
        "SNOTE": "https://gedcom.io/terms/v7/SNOTE",
        "SOUR": "https://gedcom.io/terms/v7/SOUR",
        "TYPE": "https://gedcom.io/terms/v7/TYPE",
        "UID": "https://gedcom.io/terms/v7/UID",
        "WIFE": "https://gedcom.io/terms/v7/WIFE",
        "WWW": "https://gedcom.io/terms/v7/WWW",
    },
    "https://gedcom.io/terms/v7/FAM-CENS": {
        "ADDR": "https://gedcom.io/terms/v7/ADDR",
        "AGNC": "https://gedcom.io/terms/v7/AGNC",
        "ASSO": "https://gedcom.io/terms/v7/ASSO",
        "CAUS": "https://gedcom.io/terms/v7/CAUS",
        "DATE": "https://gedcom.io/terms/v7/DATE",
        "EMAIL": "https://gedcom.io/terms/v7/EMAIL",
        "FAX": "https://gedcom.io/terms/v7/FAX",
        "HUSB": "https://gedcom.io/terms/v7/HUSB",
        "NOTE": "https://gedcom.io/terms/v7/NOTE",
        "OBJE": "https://gedcom.io/terms/v7/OBJE",
        "PHON": "https://gedcom.io/terms/v7/PHON",
        "PLAC": "https://gedcom.io/terms/v7/PLAC",
        "RELI": "https://gedcom.io/terms/v7/RELI",
        "RESN": "https://gedcom.io/terms/v7/RESN",
        "SDATE": "https://gedcom.io/terms/v7/SDATE",
        "SNOTE": "https://gedcom.io/terms/v7/SNOTE",
        "SOUR": "https://gedcom.io/terms/v7/SOUR",
        "TYPE": "https://gedcom.io/terms/v7/TYPE",
        "UID": "https://gedcom.io/terms/v7/UID",
        "WIFE": "https://gedcom.io/terms/v7/WIFE",
        "WWW": "https://gedcom.io/terms/v7/WWW",
    },
    "https://gedcom.io/terms/v7/FAM-EVEN": {
        "ADDR": "https://gedcom.io/terms/v7/ADDR",
        "AGNC": "https://gedcom.io/terms/v7/AGNC",
        "ASSO": "https://gedcom.io/terms/v7/ASSO",
        "CAUS": "https://gedcom.io/terms/v7/CAUS",
        "DATE": "https://gedcom.io/terms/v7/DATE",
        "EMAIL": "https://gedcom.io/terms/v7/EMAIL",
        "FAX": "https://gedcom.io/terms/v7/FAX",
        "HUSB": "https://gedcom.io/terms/v7/HUSB",
        "NOTE": "https://gedcom.io/terms/v7/NOTE",
        "OBJE": "https://gedcom.io/terms/v7/OBJE",
        "PHON": "https://gedcom.io/terms/v7/PHON",
        "PLAC": "https://gedcom.io/terms/v7/PLAC",
        "RELI": "https://gedcom.io/terms/v7/RELI",
        "RESN": "https://gedcom.io/terms/v7/RESN",
        "SDATE": "https://gedcom.io/terms/v7/SDATE",
        "SNOTE": "https://gedcom.io/terms/v7/SNOTE",
        "SOUR": "https://gedcom.io/terms/v7/SOUR",
        "TYPE": "https://gedcom.io/terms/v7/TYPE",
        "UID": "https://gedcom.io/terms/v7/UID",
        "WIFE": "https://gedcom.io/terms/v7/WIFE",
        "WWW": "https://gedcom.io/terms/v7/WWW",
    },
    "https://gedcom.io/terms/v7/FAM-FACT": {
        "ADDR": "https://gedcom.io/terms/v7/ADDR",
        "AGNC": "https://gedcom.io/terms/v7/AGNC",
        "ASSO": "https://gedcom.io/terms/v7/ASSO",
        "CAUS": "https://gedcom.io/terms/v7/CAUS",
        "DATE": "https://gedcom.io/terms/v7/DATE",
        "EMAIL": "https://gedcom.io/terms/v7/EMAIL",
        "FAX": "https://gedcom.io/terms/v7/FAX",
        "HUSB": "https://gedcom.io/terms/v7/HUSB",
        "NOTE": "https://gedcom.io/terms/v7/NOTE",
        "OBJE": "https://gedcom.io/terms/v7/OBJE",
        "PHON": "https://gedcom.io/terms/v7/PHON",
        "PLAC": "https://gedcom.io/terms/v7/PLAC",
        "RELI": "https://gedcom.io/terms/v7/RELI",
        "RESN": "https://gedcom.io/terms/v7/RESN",
        "SDATE": "https://gedcom.io/terms/v7/SDATE",
        "SNOTE": "https://gedcom.io/terms/v7/SNOTE",
        "SOUR": "https://gedcom.io/terms/v7/SOUR",
        "TYPE": "https://gedcom.io/terms/v7/TYPE",
        "UID": "https://gedcom.io/terms/v7/UID",
        "WIFE": "https://gedcom.io/terms/v7/WIFE",
        "WWW": "https://gedcom.io/terms/v7/WWW",
    },
    "https://gedcom.io/terms/v7/FAM-NCHI": {
        "ADDR": "https://gedcom.io/terms/v7/ADDR",
        "AGNC": "https://gedcom.io/terms/v7/AGNC",
        "ASSO": "https://gedcom.io/terms/v7/ASSO",
        "CAUS": "https://gedcom.io/terms/v7/CAUS",
        "DATE": "https://gedcom.io/terms/v7/DATE",
        "EMAIL": "https://gedcom.io/terms/v7/EMAIL",
        "FAX": "https://gedcom.io/terms/v7/FAX",
        "HUSB": "https://gedcom.io/terms/v7/HUSB",
        "NOTE": "https://gedcom.io/terms/v7/NOTE",
        "OBJE": "https://gedcom.io/terms/v7/OBJE",
        "PHON": "https://gedcom.io/terms/v7/PHON",
        "PLAC": "https://gedcom.io/terms/v7/PLAC",
        "RELI": "https://gedcom.io/terms/v7/RELI",
        "RESN": "https://gedcom.io/terms/v7/RESN",
        "SDATE": "https://gedcom.io/terms/v7/SDATE",
        "SNOTE": "https://gedcom.io/terms/v7/SNOTE",
        "SOUR": "https://gedcom.io/terms/v7/SOUR",
        "TYPE": "https://gedcom.io/terms/v7/TYPE",
        "UID": "https://gedcom.io/terms/v7/UID",
        "WIFE": "https://gedcom.io/terms/v7/WIFE",
        "WWW": "https://gedcom.io/terms/v7/WWW",
    },
    "https://gedcom.io/terms/v7/FAM-RESI": {
        "ADDR": "https://gedcom.io/terms/v7/ADDR",
        "AGNC": "https://gedcom.io/terms/v7/AGNC",
        "ASSO": "https://gedcom.io/terms/v7/ASSO",
        "CAUS": "https://gedcom.io/terms/v7/CAUS",
        "DATE": "https://gedcom.io/terms/v7/DATE",
        "EMAIL": "https://gedcom.io/terms/v7/EMAIL",
        "FAX": "https://gedcom.io/terms/v7/FAX",
        "HUSB": "https://gedcom.io/terms/v7/HUSB",
        "NOTE": "https://gedcom.io/terms/v7/NOTE",
        "OBJE": "https://gedcom.io/terms/v7/OBJE",
        "PHON": "https://gedcom.io/terms/v7/PHON",
        "PLAC": "https://gedcom.io/terms/v7/PLAC",
        "RELI": "https://gedcom.io/terms/v7/RELI",
        "RESN": "https://gedcom.io/terms/v7/RESN",
        "SDATE": "https://gedcom.io/terms/v7/SDATE",
        "SNOTE": "https://gedcom.io/terms/v7/SNOTE",
        "SOUR": "https://gedcom.io/terms/v7/SOUR",
        "TYPE": "https://gedcom.io/terms/v7/TYPE",
        "UID": "https://gedcom.io/terms/v7/UID",
        "WIFE": "https://gedcom.io/terms/v7/WIFE",
        "WWW": "https://gedcom.io/terms/v7/WWW",
    },
    "https://gedcom.io/terms/v7/FCOM": {
        "ADDR": "https://gedcom.io/terms/v7/ADDR",
        "AGE": "https://gedcom.io/terms/v7/AGE",
        "AGNC": "https://gedcom.io/terms/v7/AGNC",
        "ASSO": "https://gedcom.io/terms/v7/ASSO",
        "CAUS": "https://gedcom.io/terms/v7/CAUS",
        "DATE": "https://gedcom.io/terms/v7/DATE",
        "EMAIL": "https://gedcom.io/terms/v7/EMAIL",
        "FAX": "https://gedcom.io/terms/v7/FAX",
        "NOTE": "https://gedcom.io/terms/v7/NOTE",
        "OBJE": "https://gedcom.io/terms/v7/OBJE",
        "PHON": "https://gedcom.io/terms/v7/PHON",
        "PLAC": "https://gedcom.io/terms/v7/PLAC",
        "RELI": "https://gedcom.io/terms/v7/RELI",
        "RESN": "https://gedcom.io/terms/v7/RESN",
        "SDATE": "https://gedcom.io/terms/v7/SDATE",
        "SNOTE": "https://gedcom.io/terms/v7/SNOTE",
        "SOUR": "https://gedcom.io/terms/v7/SOUR",
        "TYPE": "https://gedcom.io/terms/v7/TYPE",
        "UID": "https://gedcom.io/terms/v7/UID",
        "WWW": "https://gedcom.io/terms/v7/WWW",
    },
    "https://gedcom.io/terms/v7/GRAD": {
        "ADDR": "https://gedcom.io/terms/v7/ADDR",
        "AGE": "https://gedcom.io/terms/v7/AGE",
        "AGNC": "https://gedcom.io/terms/v7/AGNC",
        "ASSO": "https://gedcom.io/terms/v7/ASSO",
        "CAUS": "https://gedcom.io/terms/v7/CAUS",
        "DATE": "https://gedcom.io/terms/v7/DATE",
        "EMAIL": "https://gedcom.io/terms/v7/EMAIL",
        "FAX": "https://gedcom.io/terms/v7/FAX",
        "NOTE": "https://gedcom.io/terms/v7/NOTE",
        "OBJE": "https://gedcom.io/terms/v7/OBJE",
        "PHON": "https://gedcom.io/terms/v7/PHON",
        "PLAC": "https://gedcom.io/terms/v7/PLAC",
        "RELI": "https://gedcom.io/terms/v7/RELI",
        "RESN": "https://gedcom.io/terms/v7/RESN",
        "SDATE": "https://gedcom.io/terms/v7/SDATE",
        "SNOTE": "https://gedcom.io/terms/v7/SNOTE",
        "SOUR": "https://gedcom.io/terms/v7/SOUR",
        "TYPE": "https://gedcom.io/terms/v7/TYPE",
        "UID": "https://gedcom.io/terms/v7/UID",
        "WWW": "https://gedcom.io/terms/v7/WWW",
    },
    "https://gedcom.io/terms/v7/IDNO": {
        "ADDR": "https://gedcom.io/terms/v7/ADDR",
        "AGE": "https://gedcom.io/terms/v7/AGE",
        "AGNC": "https://gedcom.io/terms/v7/AGNC",
        "ASSO": "https://gedcom.io/terms/v7/ASSO",
        "CAUS": "https://gedcom.io/terms/v7/CAUS",
        "DATE": "https://gedcom.io/terms/v7/DATE",
        "EMAIL": "https://gedcom.io/terms/v7/EMAIL",
        "FAX": "https://gedcom.io/terms/v7/FAX",
        "NOTE": "https://gedcom.io/terms/v7/NOTE",
        "OBJE": "https://gedcom.io/terms/v7/OBJE",
        "PHON": "https://gedcom.io/terms/v7/PHON",
        "PLAC": "https://gedcom.io/terms/v7/PLAC",
        "RELI": "https://gedcom.io/terms/v7/RELI",
        "RESN": "https://gedcom.io/terms/v7/RESN",
        "SDATE": "https://gedcom.io/terms/v7/SDATE",
        "SNOTE": "https://gedcom.io/terms/v7/SNOTE",
        "SOUR": "https://gedcom.io/terms/v7/SOUR",
        "TYPE": "https://gedcom.io/terms/v7/TYPE",
        "UID": "https://gedcom.io/terms/v7/UID",
        "WWW": "https://gedcom.io/terms/v7/WWW",
    },
    "https://gedcom.io/terms/v7/IMMI": {
        "ADDR": "https://gedcom.io/terms/v7/ADDR",
        "AGE": "https://gedcom.io/terms/v7/AGE",
        "AGNC": "https://gedcom.io/terms/v7/AGNC",
        "ASSO": "https://gedcom.io/terms/v7/ASSO",
        "CAUS": "https://gedcom.io/terms/v7/CAUS",
        "DATE": "https://gedcom.io/terms/v7/DATE",
        "EMAIL": "https://gedcom.io/terms/v7/EMAIL",
        "FAX": "https://gedcom.io/terms/v7/FAX",
        "NOTE": "https://gedcom.io/terms/v7/NOTE",
        "OBJE": "https://gedcom.io/terms/v7/OBJE",
        "PHON": "https://gedcom.io/terms/v7/PHON",
        "PLAC": "https://gedcom.io/terms/v7/PLAC",
        "RELI": "https://gedcom.io/terms/v7/RELI",
        "RESN": "https://gedcom.io/terms/v7/RESN",
        "SDATE": "https://gedcom.io/terms/v7/SDATE",
        "SNOTE": "https://gedcom.io/terms/v7/SNOTE",
        "SOUR": "https://gedcom.io/terms/v7/SOUR",
        "TYPE": "https://gedcom.io/terms/v7/TYPE",
        "UID": "https://gedcom.io/terms/v7/UID",
        "WWW": "https://gedcom.io/terms/v7/WWW",
    },
    "https://gedcom.io/terms/v7/INDI-CENS": {
        "ADDR": "https://gedcom.io/terms/v7/ADDR",
        "AGE": "https://gedcom.io/terms/v7/AGE",
        "AGNC": "https://gedcom.io/terms/v7/AGNC",
        "ASSO": "https://gedcom.io/terms/v7/ASSO",
        "CAUS": "https://gedcom.io/terms/v7/CAUS",
        "DATE": "https://gedcom.io/terms/v7/DATE",
        "EMAIL": "https://gedcom.io/terms/v7/EMAIL",
        "FAX": "https://gedcom.io/terms/v7/FAX",
        "NOTE": "https://gedcom.io/terms/v7/NOTE",
        "OBJE": "https://gedcom.io/terms/v7/OBJE",
        "PHON": "https://gedcom.io/terms/v7/PHON",
        "PLAC": "https://gedcom.io/terms/v7/PLAC",
        "RELI": "https://gedcom.io/terms/v7/RELI",
        "RESN": "https://gedcom.io/terms/v7/RESN",
        "SDATE": "https://gedcom.io/terms/v7/SDATE",
        "SNOTE": "https://gedcom.io/terms/v7/SNOTE",
        "SOUR": "https://gedcom.io/terms/v7/SOUR",
        "TYPE": "https://gedcom.io/terms/v7/TYPE",
        "UID": "https://gedcom.io/terms/v7/UID",
        "WWW": "https://gedcom.io/terms/v7/WWW",
    },
    "https://gedcom.io/terms/v7/INDI-EVEN": {
        "ADDR": "https://gedcom.io/terms/v7/ADDR",
        "AGE": "https://gedcom.io/terms/v7/AGE",
        "AGNC": "https://gedcom.io/terms/v7/AGNC",
        "ASSO": "https://gedcom.io/terms/v7/ASSO",
        "CAUS": "https://gedcom.io/terms/v7/CAUS",
        "DATE": "https://gedcom.io/terms/v7/DATE",
        "EMAIL": "https://gedcom.io/terms/v7/EMAIL",
        "FAX": "https://gedcom.io/terms/v7/FAX",
        "NOTE": "https://gedcom.io/terms/v7/NOTE",
        "OBJE": "https://gedcom.io/terms/v7/OBJE",
        "PHON": "https://gedcom.io/terms/v7/PHON",
        "PLAC": "https://gedcom.io/terms/v7/PLAC",
        "RELI": "https://gedcom.io/terms/v7/RELI",
        "RESN": "https://gedcom.io/terms/v7/RESN",
        "SDATE": "https://gedcom.io/terms/v7/SDATE",
        "SNOTE": "https://gedcom.io/terms/v7/SNOTE",
        "SOUR": "https://gedcom.io/terms/v7/SOUR",
        "TYPE": "https://gedcom.io/terms/v7/TYPE",
        "UID": "https://gedcom.io/terms/v7/UID",
        "WWW": "https://gedcom.io/terms/v7/WWW",
    },
    "https://gedcom.io/terms/v7/INDI-FACT": {
        "ADDR": "https://gedcom.io/terms/v7/ADDR",
        "AGE": "https://gedcom.io/terms/v7/AGE",
        "AGNC": "https://gedcom.io/terms/v7/AGNC",
        "ASSO": "https://gedcom.io/terms/v7/ASSO",
        "CAUS": "https://gedcom.io/terms/v7/CAUS",
        "DATE": "https://gedcom.io/terms/v7/DATE",
        "EMAIL": "https://gedcom.io/terms/v7/EMAIL",
        "FAX": "https://gedcom.io/terms/v7/FAX",
        "NOTE": "https://gedcom.io/terms/v7/NOTE",
        "OBJE": "https://gedcom.io/terms/v7/OBJE",
        "PHON": "https://gedcom.io/terms/v7/PHON",
        "PLAC": "https://gedcom.io/terms/v7/PLAC",
        "RELI": "https://gedcom.io/terms/v7/RELI",
        "RESN": "https://gedcom.io/terms/v7/RESN",
        "SDATE": "https://gedcom.io/terms/v7/SDATE",
        "SNOTE": "https://gedcom.io/terms/v7/SNOTE",
        "SOUR": "https://gedcom.io/terms/v7/SOUR",
        "TYPE": "https://gedcom.io/terms/v7/TYPE",
        "UID": "https://gedcom.io/terms/v7/UID",
        "WWW": "https://gedcom.io/terms/v7/WWW",
    },
    "https://gedcom.io/terms/v7/INDI-NCHI": {
        "ADDR": "https://gedcom.io/terms/v7/ADDR",
        "AGE": "https://gedcom.io/terms/v7/AGE",
        "AGNC": "https://gedcom.io/terms/v7/AGNC",
        "ASSO": "https://gedcom.io/terms/v7/ASSO",
        "CAUS": "https://gedcom.io/terms/v7/CAUS",
        "DATE": "https://gedcom.io/terms/v7/DATE",
        "EMAIL": "https://gedcom.io/terms/v7/EMAIL",
        "FAX": "https://gedcom.io/terms/v7/FAX",
        "NOTE": "https://gedcom.io/terms/v7/NOTE",
        "OBJE": "https://gedcom.io/terms/v7/OBJE",
        "PHON": "https://gedcom.io/terms/v7/PHON",
        "PLAC": "https://gedcom.io/terms/v7/PLAC",
        "RELI": "https://gedcom.io/terms/v7/RELI",
        "RESN": "https://gedcom.io/terms/v7/RESN",
        "SDATE": "https://gedcom.io/terms/v7/SDATE",
        "SNOTE": "https://gedcom.io/terms/v7/SNOTE",
        "SOUR": "https://gedcom.io/terms/v7/SOUR",
        "TYPE": "https://gedcom.io/terms/v7/TYPE",
        "UID": "https://gedcom.io/terms/v7/UID",
        "WWW": "https://gedcom.io/terms/v7/WWW",
    },
    "https://gedcom.io/terms/v7/INDI-RELI": {
        "ADDR": "https://gedcom.io/terms/v7/ADDR",
        "AGE": "https://gedcom.io/terms/v7/AGE",
        "AGNC": "https://gedcom.io/terms/v7/AGNC",
        "ASSO": "https://gedcom.io/terms/v7/ASSO",
        "CAUS": "https://gedcom.io/terms/v7/CAUS",
        "DATE": "https://gedcom.io/terms/v7/DATE",
        "EMAIL": "https://gedcom.io/terms/v7/EMAIL",
        "FAX": "https://gedcom.io/terms/v7/FAX",
        "NOTE": "https://gedcom.io/terms/v7/NOTE",
        "OBJE": "https://gedcom.io/terms/v7/OBJE",
        "PHON": "https://gedcom.io/terms/v7/PHON",
        "PLAC": "https://gedcom.io/terms/v7/PLAC",
        "RELI": "https://gedcom.io/terms/v7/RELI",
        "RESN": "https://gedcom.io/terms/v7/RESN",
        "SDATE": "https://gedcom.io/terms/v7/SDATE",
        "SNOTE": "https://gedcom.io/terms/v7/SNOTE",
        "SOUR": "https://gedcom.io/terms/v7/SOUR",
        "TYPE": "https://gedcom.io/terms/v7/TYPE",
        "UID": "https://gedcom.io/terms/v7/UID",
        "WWW": "https://gedcom.io/terms/v7/WWW",
    },
    "https://gedcom.io/terms/v7/INDI-RESI": {
        "ADDR": "https://gedcom.io/terms/v7/ADDR",
        "AGE": "https://gedcom.io/terms/v7/AGE",
        "AGNC": "https://gedcom.io/terms/v7/AGNC",
        "ASSO": "https://gedcom.io/terms/v7/ASSO",
        "CAUS": "https://gedcom.io/terms/v7/CAUS",
        "DATE": "https://gedcom.io/terms/v7/DATE",
        "EMAIL": "https://gedcom.io/terms/v7/EMAIL",
        "FAX": "https://gedcom.io/terms/v7/FAX",
        "NOTE": "https://gedcom.io/terms/v7/NOTE",
        "OBJE": "https://gedcom.io/terms/v7/OBJE",
        "PHON": "https://gedcom.io/terms/v7/PHON",
        "PLAC": "https://gedcom.io/terms/v7/PLAC",
        "RELI": "https://gedcom.io/terms/v7/RELI",
        "RESN": "https://gedcom.io/terms/v7/RESN",
        "SDATE": "https://gedcom.io/terms/v7/SDATE",
        "SNOTE": "https://gedcom.io/terms/v7/SNOTE",
        "SOUR": "https://gedcom.io/terms/v7/SOUR",
        "TYPE": "https://gedcom.io/terms/v7/TYPE",
        "UID": "https://gedcom.io/terms/v7/UID",
        "WWW": "https://gedcom.io/terms/v7/WWW",
    },
    "https://gedcom.io/terms/v7/INDI-TITL": {
        "ADDR": "https://gedcom.io/terms/v7/ADDR",
        "AGE": "https://gedcom.io/terms/v7/AGE",
        "AGNC": "https://gedcom.io/terms/v7/AGNC",
        "ASSO": "https://gedcom.io/terms/v7/ASSO",
        "CAUS": "https://gedcom.io/terms/v7/CAUS",
        "DATE": "https://gedcom.io/terms/v7/DATE",
        "EMAIL": "https://gedcom.io/terms/v7/EMAIL",
        "FAX": "https://gedcom.io/terms/v7/FAX",
        "NOTE": "https://gedcom.io/terms/v7/NOTE",
        "OBJE": "https://gedcom.io/terms/v7/OBJE",
        "PHON": "https://gedcom.io/terms/v7/PHON",
        "PLAC": "https://gedcom.io/terms/v7/PLAC",
        "RELI": "https://gedcom.io/terms/v7/RELI",
        "RESN": "https://gedcom.io/terms/v7/RESN",
        "SDATE": "https://gedcom.io/terms/v7/SDATE",
        "SNOTE": "https://gedcom.io/terms/v7/SNOTE",
        "SOUR": "https://gedcom.io/terms/v7/SOUR",
        "TYPE": "https://gedcom.io/terms/v7/TYPE",
        "UID": "https://gedcom.io/terms/v7/UID",
        "WWW": "https://gedcom.io/terms/v7/WWW",
    },
    "https://gedcom.io/terms/v7/MARB": {
        "ADDR": "https://gedcom.io/terms/v7/ADDR",
        "AGNC": "https://gedcom.io/terms/v7/AGNC",
        "ASSO": "https://gedcom.io/terms/v7/ASSO",
        "CAUS": "https://gedcom.io/terms/v7/CAUS",
        "DATE": "https://gedcom.io/terms/v7/DATE",
        "EMAIL": "https://gedcom.io/terms/v7/EMAIL",
        "FAX": "https://gedcom.io/terms/v7/FAX",
        "HUSB": "https://gedcom.io/terms/v7/HUSB",
        "NOTE": "https://gedcom.io/terms/v7/NOTE",
        "OBJE": "https://gedcom.io/terms/v7/OBJE",
        "PHON": "https://gedcom.io/terms/v7/PHON",
        "PLAC": "https://gedcom.io/terms/v7/PLAC",
        "RELI": "https://gedcom.io/terms/v7/RELI",
        "RESN": "https://gedcom.io/terms/v7/RESN",
        "SDATE": "https://gedcom.io/terms/v7/SDATE",
        "SNOTE": "https://gedcom.io/terms/v7/SNOTE",
        "SOUR": "https://gedcom.io/terms/v7/SOUR",
        "TYPE": "https://gedcom.io/terms/v7/TYPE",
        "UID": "https://gedcom.io/terms/v7/UID",
        "WIFE": "https://gedcom.io/terms/v7/WIFE",
        "WWW": "https://gedcom.io/terms/v7/WWW",
    },
    "https://gedcom.io/terms/v7/MARC": {
        "ADDR": "https://gedcom.io/terms/v7/ADDR",
        "AGNC": "https://gedcom.io/terms/v7/AGNC",
        "ASSO": "https://gedcom.io/terms/v7/ASSO",
        "CAUS": "https://gedcom.io/terms/v7/CAUS",
        "DATE": "https://gedcom.io/terms/v7/DATE",
        "EMAIL": "https://gedcom.io/terms/v7/EMAIL",
        "FAX": "https://gedcom.io/terms/v7/FAX",
        "HUSB": "https://gedcom.io/terms/v7/HUSB",
        "NOTE": "https://gedcom.io/terms/v7/NOTE",
        "OBJE": "https://gedcom.io/terms/v7/OBJE",
        "PHON": "https://gedcom.io/terms/v7/PHON",
        "PLAC": "https://gedcom.io/terms/v7/PLAC",
        "RELI": "https://gedcom.io/terms/v7/RELI",
        "RESN": "https://gedcom.io/terms/v7/RESN",
        "SDATE": "https://gedcom.io/terms/v7/SDATE",
        "SNOTE": "https://gedcom.io/terms/v7/SNOTE",
        "SOUR": "https://gedcom.io/terms/v7/SOUR",
        "TYPE": "https://gedcom.io/terms/v7/TYPE",
        "UID": "https://gedcom.io/terms/v7/UID",
        "WIFE": "https://gedcom.io/terms/v7/WIFE",
        "WWW": "https://gedcom.io/terms/v7/WWW",
    },
    "https://gedcom.io/terms/v7/MARL": {
        "ADDR": "https://gedcom.io/terms/v7/ADDR",
        "AGNC": "https://gedcom.io/terms/v7/AGNC",
        "ASSO": "https://gedcom.io/terms/v7/ASSO",
        "CAUS": "https://gedcom.io/terms/v7/CAUS",
        "DATE": "https://gedcom.io/terms/v7/DATE",
        "EMAIL": "https://gedcom.io/terms/v7/EMAIL",
        "FAX": "https://gedcom.io/terms/v7/FAX",
        "HUSB": "https://gedcom.io/terms/v7/HUSB",
        "NOTE": "https://gedcom.io/terms/v7/NOTE",
        "OBJE": "https://gedcom.io/terms/v7/OBJE",
        "PHON": "https://gedcom.io/terms/v7/PHON",
        "PLAC": "https://gedcom.io/terms/v7/PLAC",
        "RELI": "https://gedcom.io/terms/v7/RELI",
        "RESN": "https://gedcom.io/terms/v7/RESN",
        "SDATE": "https://gedcom.io/terms/v7/SDATE",
        "SNOTE": "https://gedcom.io/terms/v7/SNOTE",
        "SOUR": "https://gedcom.io/terms/v7/SOUR",
        "TYPE": "https://gedcom.io/terms/v7/TYPE",
        "UID": "https://gedcom.io/terms/v7/UID",
        "WIFE": "https://gedcom.io/terms/v7/WIFE",
        "WWW": "https://gedcom.io/terms/v7/WWW",
    },
    "https://gedcom.io/terms/v7/MARR": {
        "ADDR": "https://gedcom.io/terms/v7/ADDR",
        "AGNC": "https://gedcom.io/terms/v7/AGNC",
        "ASSO": "https://gedcom.io/terms/v7/ASSO",
        "CAUS": "https://gedcom.io/terms/v7/CAUS",
        "DATE": "https://gedcom.io/terms/v7/DATE",
        "EMAIL": "https://gedcom.io/terms/v7/EMAIL",
        "FAX": "https://gedcom.io/terms/v7/FAX",
        "HUSB": "https://gedcom.io/terms/v7/HUSB",
        "NOTE": "https://gedcom.io/terms/v7/NOTE",
        "OBJE": "https://gedcom.io/terms/v7/OBJE",
        "PHON": "https://gedcom.io/terms/v7/PHON",
        "PLAC": "https://gedcom.io/terms/v7/PLAC",
        "RELI": "https://gedcom.io/terms/v7/RELI",
        "RESN": "https://gedcom.io/terms/v7/RESN",
        "SDATE": "https://gedcom.io/terms/v7/SDATE",
        "SNOTE": "https://gedcom.io/terms/v7/SNOTE",
        "SOUR": "https://gedcom.io/terms/v7/SOUR",
        "TYPE": "https://gedcom.io/terms/v7/TYPE",
        "UID": "https://gedcom.io/terms/v7/UID",
        "WIFE": "https://gedcom.io/terms/v7/WIFE",
        "WWW": "https://gedcom.io/terms/v7/WWW",
    },
    "https://gedcom.io/terms/v7/MARS": {
        "ADDR": "https://gedcom.io/terms/v7/ADDR",
        "AGNC": "https://gedcom.io/terms/v7/AGNC",
        "ASSO": "https://gedcom.io/terms/v7/ASSO",
        "CAUS": "https://gedcom.io/terms/v7/CAUS",
        "DATE": "https://gedcom.io/terms/v7/DATE",
        "EMAIL": "https://gedcom.io/terms/v7/EMAIL",
        "FAX": "https://gedcom.io/terms/v7/FAX",
        "HUSB": "https://gedcom.io/terms/v7/HUSB",
        "NOTE": "https://gedcom.io/terms/v7/NOTE",
        "OBJE": "https://gedcom.io/terms/v7/OBJE",
        "PHON": "https://gedcom.io/terms/v7/PHON",
        "PLAC": "https://gedcom.io/terms/v7/PLAC",
        "RELI": "https://gedcom.io/terms/v7/RELI",
        "RESN": "https://gedcom.io/terms/v7/RESN",
        "SDATE": "https://gedcom.io/terms/v7/SDATE",
        "SNOTE": "https://gedcom.io/terms/v7/SNOTE",
        "SOUR": "https://gedcom.io/terms/v7/SOUR",
        "TYPE": "https://gedcom.io/terms/v7/TYPE",
        "UID": "https://gedcom.io/terms/v7/UID",
        "WIFE": "https://gedcom.io/terms/v7/WIFE",
        "WWW": "https://gedcom.io/terms/v7/WWW",
    },
    "https://gedcom.io/terms/v7/NATI": {
        "ADDR": "https://gedcom.io/terms/v7/ADDR",
        "AGE": "https://gedcom.io/terms/v7/AGE",
        "AGNC": "https://gedcom.io/terms/v7/AGNC",
        "ASSO": "https://gedcom.io/terms/v7/ASSO",
        "CAUS": "https://gedcom.io/terms/v7/CAUS",
        "DATE": "https://gedcom.io/terms/v7/DATE",
        "EMAIL": "https://gedcom.io/terms/v7/EMAIL",
        "FAX": "https://gedcom.io/terms/v7/FAX",
        "NOTE": "https://gedcom.io/terms/v7/NOTE",
        "OBJE": "https://gedcom.io/terms/v7/OBJE",
        "PHON": "https://gedcom.io/terms/v7/PHON",
        "PLAC": "https://gedcom.io/terms/v7/PLAC",
        "RELI": "https://gedcom.io/terms/v7/RELI",
        "RESN": "https://gedcom.io/terms/v7/RESN",
        "SDATE": "https://gedcom.io/terms/v7/SDATE",
        "SNOTE": "https://gedcom.io/terms/v7/SNOTE",
        "SOUR": "https://gedcom.io/terms/v7/SOUR",
        "TYPE": "https://gedcom.io/terms/v7/TYPE",
        "UID": "https://gedcom.io/terms/v7/UID",
        "WWW": "https://gedcom.io/terms/v7/WWW",
    },
    "https://gedcom.io/terms/v7/NATU": {
        "ADDR": "https://gedcom.io/terms/v7/ADDR",
        "AGE": "https://gedcom.io/terms/v7/AGE",
        "AGNC": "https://gedcom.io/terms/v7/AGNC",
        "ASSO": "https://gedcom.io/terms/v7/ASSO",
        "CAUS": "https://gedcom.io/terms/v7/CAUS",
        "DATE": "https://gedcom.io/terms/v7/DATE",
        "EMAIL": "https://gedcom.io/terms/v7/EMAIL",
        "FAX": "https://gedcom.io/terms/v7/FAX",
        "NOTE": "https://gedcom.io/terms/v7/NOTE",
        "OBJE": "https://gedcom.io/terms/v7/OBJE",
        "PHON": "https://gedcom.io/terms/v7/PHON",
        "PLAC": "https://gedcom.io/terms/v7/PLAC",
        "RELI": "https://gedcom.io/terms/v7/RELI",
        "RESN": "https://gedcom.io/terms/v7/RESN",
        "SDATE": "https://gedcom.io/terms/v7/SDATE",
        "SNOTE": "https://gedcom.io/terms/v7/SNOTE",
        "SOUR": "https://gedcom.io/terms/v7/SOUR",
        "TYPE": "https://gedcom.io/terms/v7/TYPE",
        "UID": "https://gedcom.io/terms/v7/UID",
        "WWW": "https://gedcom.io/terms/v7/WWW",
    },
    "https://gedcom.io/terms/v7/NMR": {
        "ADDR": "https://gedcom.io/terms/v7/ADDR",
        "AGE": "https://gedcom.io/terms/v7/AGE",
        "AGNC": "https://gedcom.io/terms/v7/AGNC",
        "ASSO": "https://gedcom.io/terms/v7/ASSO",
        "CAUS": "https://gedcom.io/terms/v7/CAUS",
        "DATE": "https://gedcom.io/terms/v7/DATE",
        "EMAIL": "https://gedcom.io/terms/v7/EMAIL",
        "FAX": "https://gedcom.io/terms/v7/FAX",
        "NOTE": "https://gedcom.io/terms/v7/NOTE",
        "OBJE": "https://gedcom.io/terms/v7/OBJE",
        "PHON": "https://gedcom.io/terms/v7/PHON",
        "PLAC": "https://gedcom.io/terms/v7/PLAC",
        "RELI": "https://gedcom.io/terms/v7/RELI",
        "RESN": "https://gedcom.io/terms/v7/RESN",
        "SDATE": "https://gedcom.io/terms/v7/SDATE",
        "SNOTE": "https://gedcom.io/terms/v7/SNOTE",
        "SOUR": "https://gedcom.io/terms/v7/SOUR",
        "TYPE": "https://gedcom.io/terms/v7/TYPE",
        "UID": "https://gedcom.io/terms/v7/UID",
        "WWW": "https://gedcom.io/terms/v7/WWW",
    },
    "https://gedcom.io/terms/v7/OCCU": {
        "ADDR": "https://gedcom.io/terms/v7/ADDR",
        "AGE": "https://gedcom.io/terms/v7/AGE",
        "AGNC": "https://gedcom.io/terms/v7/AGNC",
        "ASSO": "https://gedcom.io/terms/v7/ASSO",
        "CAUS": "https://gedcom.io/terms/v7/CAUS",
        "DATE": "https://gedcom.io/terms/v7/DATE",
        "EMAIL": "https://gedcom.io/terms/v7/EMAIL",
        "FAX": "https://gedcom.io/terms/v7/FAX",
        "NOTE": "https://gedcom.io/terms/v7/NOTE",
        "OBJE": "https://gedcom.io/terms/v7/OBJE",
        "PHON": "https://gedcom.io/terms/v7/PHON",
        "PLAC": "https://gedcom.io/terms/v7/PLAC",
        "RELI": "https://gedcom.io/terms/v7/RELI",
        "RESN": "https://gedcom.io/terms/v7/RESN",
        "SDATE": "https://gedcom.io/terms/v7/SDATE",
        "SNOTE": "https://gedcom.io/terms/v7/SNOTE",
        "SOUR": "https://gedcom.io/terms/v7/SOUR",
        "TYPE": "https://gedcom.io/terms/v7/TYPE",
        "UID": "https://gedcom.io/terms/v7/UID",
        "WWW": "https://gedcom.io/terms/v7/WWW",
    },
    "https://gedcom.io/terms/v7/ORDN": {
        "ADDR": "https://gedcom.io/terms/v7/ADDR",
        "AGE": "https://gedcom.io/terms/v7/AGE",
        "AGNC": "https://gedcom.io/terms/v7/AGNC",
        "ASSO": "https://gedcom.io/terms/v7/ASSO",
        "CAUS": "https://gedcom.io/terms/v7/CAUS",
        "DATE": "https://gedcom.io/terms/v7/DATE",
        "EMAIL": "https://gedcom.io/terms/v7/EMAIL",
        "FAX": "https://gedcom.io/terms/v7/FAX",
        "NOTE": "https://gedcom.io/terms/v7/NOTE",
        "OBJE": "https://gedcom.io/terms/v7/OBJE",
        "PHON": "https://gedcom.io/terms/v7/PHON",
        "PLAC": "https://gedcom.io/terms/v7/PLAC",
        "RELI": "https://gedcom.io/terms/v7/RELI",
        "RESN": "https://gedcom.io/terms/v7/RESN",
        "SDATE": "https://gedcom.io/terms/v7/SDATE",
        "SNOTE": "https://gedcom.io/terms/v7/SNOTE",
        "SOUR": "https://gedcom.io/terms/v7/SOUR",
        "TYPE": "https://gedcom.io/terms/v7/TYPE",
        "UID": "https://gedcom.io/terms/v7/UID",
        "WWW": "https://gedcom.io/terms/v7/WWW",
    },
    "https://gedcom.io/terms/v7/PROB": {
        "ADDR": "https://gedcom.io/terms/v7/ADDR",
        "AGE": "https://gedcom.io/terms/v7/AGE",
        "AGNC": "https://gedcom.io/terms/v7/AGNC",
        "ASSO": "https://gedcom.io/terms/v7/ASSO",
        "CAUS": "https://gedcom.io/terms/v7/CAUS",
        "DATE": "https://gedcom.io/terms/v7/DATE",
        "EMAIL": "https://gedcom.io/terms/v7/EMAIL",
        "FAX": "https://gedcom.io/terms/v7/FAX",
        "NOTE": "https://gedcom.io/terms/v7/NOTE",
        "OBJE": "https://gedcom.io/terms/v7/OBJE",
        "PHON": "https://gedcom.io/terms/v7/PHON",
        "PLAC": "https://gedcom.io/terms/v7/PLAC",
        "RELI": "https://gedcom.io/terms/v7/RELI",
        "RESN": "https://gedcom.io/terms/v7/RESN",
        "SDATE": "https://gedcom.io/terms/v7/SDATE",
        "SNOTE": "https://gedcom.io/terms/v7/SNOTE",
        "SOUR": "https://gedcom.io/terms/v7/SOUR",
        "TYPE": "https://gedcom.io/terms/v7/TYPE",
        "UID": "https://gedcom.io/terms/v7/UID",
        "WWW": "https://gedcom.io/terms/v7/WWW",
    },
    "https://gedcom.io/terms/v7/PROP": {
        "ADDR": "https://gedcom.io/terms/v7/ADDR",
        "AGE": "https://gedcom.io/terms/v7/AGE",
        "AGNC": "https://gedcom.io/terms/v7/AGNC",
        "ASSO": "https://gedcom.io/terms/v7/ASSO",
        "CAUS": "https://gedcom.io/terms/v7/CAUS",
        "DATE": "https://gedcom.io/terms/v7/DATE",
        "EMAIL": "https://gedcom.io/terms/v7/EMAIL",
        "FAX": "https://gedcom.io/terms/v7/FAX",
        "NOTE": "https://gedcom.io/terms/v7/NOTE",
        "OBJE": "https://gedcom.io/terms/v7/OBJE",
        "PHON": "https://gedcom.io/terms/v7/PHON",
        "PLAC": "https://gedcom.io/terms/v7/PLAC",
        "RELI": "https://gedcom.io/terms/v7/RELI",
        "RESN": "https://gedcom.io/terms/v7/RESN",
        "SDATE": "https://gedcom.io/terms/v7/SDATE",
        "SNOTE": "https://gedcom.io/terms/v7/SNOTE",
        "SOUR": "https://gedcom.io/terms/v7/SOUR",
        "TYPE": "https://gedcom.io/terms/v7/TYPE",
        "UID": "https://gedcom.io/terms/v7/UID",
        "WWW": "https://gedcom.io/terms/v7/WWW",
    },
    "https://gedcom.io/terms/v7/RETI": {
        "ADDR": "https://gedcom.io/terms/v7/ADDR",
        "AGE": "https://gedcom.io/terms/v7/AGE",
        "AGNC": "https://gedcom.io/terms/v7/AGNC",
        "ASSO": "https://gedcom.io/terms/v7/ASSO",
        "CAUS": "https://gedcom.io/terms/v7/CAUS",
        "DATE": "https://gedcom.io/terms/v7/DATE",
        "EMAIL": "https://gedcom.io/terms/v7/EMAIL",
        "FAX": "https://gedcom.io/terms/v7/FAX",
        "NOTE": "https://gedcom.io/terms/v7/NOTE",
        "OBJE": "https://gedcom.io/terms/v7/OBJE",
        "PHON": "https://gedcom.io/terms/v7/PHON",
        "PLAC": "https://gedcom.io/terms/v7/PLAC",
        "RELI": "https://gedcom.io/terms/v7/RELI",
        "RESN": "https://gedcom.io/terms/v7/RESN",
        "SDATE": "https://gedcom.io/terms/v7/SDATE",
        "SNOTE": "https://gedcom.io/terms/v7/SNOTE",
        "SOUR": "https://gedcom.io/terms/v7/SOUR",
        "TYPE": "https://gedcom.io/terms/v7/TYPE",
        "UID": "https://gedcom.io/terms/v7/UID",
        "WWW": "https://gedcom.io/terms/v7/WWW",
    },
    "https://gedcom.io/terms/v7/SSN": {
        "ADDR": "https://gedcom.io/terms/v7/ADDR",
        "AGE": "https://gedcom.io/terms/v7/AGE",
        "AGNC": "https://gedcom.io/terms/v7/AGNC",
        "ASSO": "https://gedcom.io/terms/v7/ASSO",
        "CAUS": "https://gedcom.io/terms/v7/CAUS",
        "DATE": "https://gedcom.io/terms/v7/DATE",
        "EMAIL": "https://gedcom.io/terms/v7/EMAIL",
        "FAX": "https://gedcom.io/terms/v7/FAX",
        "NOTE": "https://gedcom.io/terms/v7/NOTE",
        "OBJE": "https://gedcom.io/terms/v7/OBJE",
        "PHON": "https://gedcom.io/terms/v7/PHON",
        "PLAC": "https://gedcom.io/terms/v7/PLAC",
        "RELI": "https://gedcom.io/terms/v7/RELI",
        "RESN": "https://gedcom.io/terms/v7/RESN",
        "SDATE": "https://gedcom.io/terms/v7/SDATE",
        "SNOTE": "https://gedcom.io/terms/v7/SNOTE",
        "SOUR": "https://gedcom.io/terms/v7/SOUR",
        "TYPE": "https://gedcom.io/terms/v7/TYPE",
        "UID": "https://gedcom.io/terms/v7/UID",
        "WWW": "https://gedcom.io/terms/v7/WWW",
    },
    "https://gedcom.io/terms/v7/WILL": {
        "ADDR": "https://gedcom.io/terms/v7/ADDR",
        "AGE": "https://gedcom.io/terms/v7/AGE",
        "AGNC": "https://gedcom.io/terms/v7/AGNC",
        "ASSO": "https://gedcom.io/terms/v7/ASSO",
        "CAUS": "https://gedcom.io/terms/v7/CAUS",
        "DATE": "https://gedcom.io/terms/v7/DATE",
        "EMAIL": "https://gedcom.io/terms/v7/EMAIL",
        "FAX": "https://gedcom.io/terms/v7/FAX",
        "NOTE": "https://gedcom.io/terms/v7/NOTE",
        "OBJE": "https://gedcom.io/terms/v7/OBJE",
        "PHON": "https://gedcom.io/terms/v7/PHON",
        "PLAC": "https://gedcom.io/terms/v7/PLAC",
        "RELI": "https://gedcom.io/terms/v7/RELI",
        "RESN": "https://gedcom.io/terms/v7/RESN",
        "SDATE": "https://gedcom.io/terms/v7/SDATE",
        "SNOTE": "https://gedcom.io/terms/v7/SNOTE",
        "SOUR": "https://gedcom.io/terms/v7/SOUR",
        "TYPE": "https://gedcom.io/terms/v7/TYPE",
        "UID": "https://gedcom.io/terms/v7/UID",
        "WWW": "https://gedcom.io/terms/v7/WWW",
    },
    "https://gedcom.io/terms/v7/record-REPO": {
        "ADDR": "https://gedcom.io/terms/v7/ADDR",
        "CHAN": "https://gedcom.io/terms/v7/CHAN",
        "CREA": "https://gedcom.io/terms/v7/CREA",
        "EMAIL": "https://gedcom.io/terms/v7/EMAIL",
        "EXID": "https://gedcom.io/terms/v7/EXID",
        "FAX": "https://gedcom.io/terms/v7/FAX",
        "NAME": "https://gedcom.io/terms/v7/NAME",
        "NOTE": "https://gedcom.io/terms/v7/NOTE",
        "PHON": "https://gedcom.io/terms/v7/PHON",
        "REFN": "https://gedcom.io/terms/v7/REFN",
        "SNOTE": "https://gedcom.io/terms/v7/SNOTE",
        "UID": "https://gedcom.io/terms/v7/UID",
        "WWW": "https://gedcom.io/terms/v7/WWW",
    },
    "https://gedcom.io/terms/v7/record-SUBM": {
        "ADDR": "https://gedcom.io/terms/v7/ADDR",
        "CHAN": "https://gedcom.io/terms/v7/CHAN",
        "CREA": "https://gedcom.io/terms/v7/CREA",
        "EMAIL": "https://gedcom.io/terms/v7/EMAIL",
        "EXID": "https://gedcom.io/terms/v7/EXID",
        "FAX": "https://gedcom.io/terms/v7/FAX",
        "LANG": "https://gedcom.io/terms/v7/SUBM-LANG",
        "NAME": "https://gedcom.io/terms/v7/NAME",
        "NOTE": "https://gedcom.io/terms/v7/NOTE",
        "OBJE": "https://gedcom.io/terms/v7/OBJE",
        "PHON": "https://gedcom.io/terms/v7/PHON",
        "REFN": "https://gedcom.io/terms/v7/REFN",
        "SNOTE": "https://gedcom.io/terms/v7/SNOTE",
        "UID": "https://gedcom.io/terms/v7/UID",
        "WWW": "https://gedcom.io/terms/v7/WWW",
    },
    "https://gedcom.io/terms/v7/record-INDI": {
        "ADOP": "https://gedcom.io/terms/v7/ADOP",
        "ALIA": "https://gedcom.io/terms/v7/ALIA",
        "ANCI": "https://gedcom.io/terms/v7/ANCI",
        "ASSO": "https://gedcom.io/terms/v7/ASSO",
        "BAPL": "https://gedcom.io/terms/v7/BAPL",
        "BAPM": "https://gedcom.io/terms/v7/BAPM",
        "BARM": "https://gedcom.io/terms/v7/BARM",
        "BASM": "https://gedcom.io/terms/v7/BASM",
        "BIRT": "https://gedcom.io/terms/v7/BIRT",
        "BLES": "https://gedcom.io/terms/v7/BLES",
        "BURI": "https://gedcom.io/terms/v7/BURI",
        "CAST": "https://gedcom.io/terms/v7/CAST",
        "CENS": "https://gedcom.io/terms/v7/INDI-CENS",
        "CHAN": "https://gedcom.io/terms/v7/CHAN",
        "CHRA": "https://gedcom.io/terms/v7/CHRA",
        "CHR": "https://gedcom.io/terms/v7/CHR",
        "CONF": "https://gedcom.io/terms/v7/CONF",
        "CONL": "https://gedcom.io/terms/v7/CONL",
        "CREA": "https://gedcom.io/terms/v7/CREA",
        "CREM": "https://gedcom.io/terms/v7/CREM",
        "DEAT": "https://gedcom.io/terms/v7/DEAT",
        "DESI": "https://gedcom.io/terms/v7/DESI",
        "DSCR": "https://gedcom.io/terms/v7/DSCR",
        "EDUC": "https://gedcom.io/terms/v7/EDUC",
        "EMIG": "https://gedcom.io/terms/v7/EMIG",
        "ENDL": "https://gedcom.io/terms/v7/ENDL",
        "EVEN": "https://gedcom.io/terms/v7/INDI-EVEN",
        "EXID": "https://gedcom.io/terms/v7/EXID",
        "FACT": "https://gedcom.io/terms/v7/INDI-FACT",
        "FAMC": "https://gedcom.io/terms/v7/INDI-FAMC",
        "FAMS": "https://gedcom.io/terms/v7/FAMS",
        "FCOM": "https://gedcom.io/terms/v7/FCOM",
        "GRAD": "https://gedcom.io/terms/v7/GRAD",
        "IDNO": "https://gedcom.io/terms/v7/IDNO",
        "IMMI": "https://gedcom.io/terms/v7/IMMI",
        "INIL": "https://gedcom.io/terms/v7/INIL",
        "NAME": "https://gedcom.io/terms/v7/INDI-NAME",
        "NATI": "https://gedcom.io/terms/v7/NATI",
        "NATU": "https://gedcom.io/terms/v7/NATU",
        "NCHI": "https://gedcom.io/terms/v7/INDI-NCHI",
        "NMR": "https://gedcom.io/terms/v7/NMR",
        "NO": "https://gedcom.io/terms/v7/NO",
        "NOTE": "https://gedcom.io/terms/v7/NOTE",
        "OBJE": "https://gedcom.io/terms/v7/OBJE",
        "OCCU": "https://gedcom.io/terms/v7/OCCU",
        "ORDN": "https://gedcom.io/terms/v7/ORDN",
        "PROB": "https://gedcom.io/terms/v7/PROB",
        "PROP": "https://gedcom.io/terms/v7/PROP",
        "REFN": "https://gedcom.io/terms/v7/REFN",
        "RELI": "https://gedcom.io/terms/v7/INDI-RELI",
        "RESN": "https://gedcom.io/terms/v7/RESN",
        "RESI": "https://gedcom.io/terms/v7/INDI-RESI",
        "RETI": "https://gedcom.io/terms/v7/RETI",
        "SEX": "https://gedcom.io/terms/v7/SEX",
        "SLGC": "https://gedcom.io/terms/v7/SLGC",
        "SNOTE": "https://gedcom.io/terms/v7/SNOTE",
        "SOUR": "https://gedcom.io/terms/v7/SOUR",
        "SSN": "https://gedcom.io/terms/v7/SSN",
        "SUBM": "https://gedcom.io/terms/v7/SUBM",
        "TITL": "https://gedcom.io/terms/v7/INDI-TITL",
        "UID": "https://gedcom.io/terms/v7/UID",
        "WILL": "https://gedcom.io/terms/v7/WILL",
    },
    "https://gedcom.io/terms/v7/ADOP-FAMC": {
        "ADOP": "https://gedcom.io/terms/v7/FAMC-ADOP"
    },
    "https://gedcom.io/terms/v7/ADDR": {
        "ADR1": "https://gedcom.io/terms/v7/ADR1",
        "ADR2": "https://gedcom.io/terms/v7/ADR2",
        "ADR3": "https://gedcom.io/terms/v7/ADR3",
        "CITY": "https://gedcom.io/terms/v7/CITY",
        "CTRY": "https://gedcom.io/terms/v7/CTRY",
        "POST": "https://gedcom.io/terms/v7/POST",
        "STAE": "https://gedcom.io/terms/v7/STAE",
    },
    "https://gedcom.io/terms/v7/HUSB": {"AGE": "https://gedcom.io/terms/v7/AGE"},
    "https://gedcom.io/terms/v7/WIFE": {"AGE": "https://gedcom.io/terms/v7/AGE"},
    "https://gedcom.io/terms/v7/DATA": {
        "AGNC": "https://gedcom.io/terms/v7/AGNC",
        "EVEN": "https://gedcom.io/terms/v7/DATA-EVEN",
        "NOTE": "https://gedcom.io/terms/v7/NOTE",
        "SNOTE": "https://gedcom.io/terms/v7/SNOTE",
    },
    "https://gedcom.io/terms/v7/record-FAM": {
        "ANUL": "https://gedcom.io/terms/v7/ANUL",
        "ASSO": "https://gedcom.io/terms/v7/ASSO",
        "CENS": "https://gedcom.io/terms/v7/FAM-CENS",
        "CHAN": "https://gedcom.io/terms/v7/CHAN",
        "CHIL": "https://gedcom.io/terms/v7/CHIL",
        "CREA": "https://gedcom.io/terms/v7/CREA",
        "DIVF": "https://gedcom.io/terms/v7/DIVF",
        "DIV": "https://gedcom.io/terms/v7/DIV",
        "ENGA": "https://gedcom.io/terms/v7/ENGA",
        "EVEN": "https://gedcom.io/terms/v7/FAM-EVEN",
        "EXID": "https://gedcom.io/terms/v7/EXID",
        "FACT": "https://gedcom.io/terms/v7/FAM-FACT",
        "HUSB": "https://gedcom.io/terms/v7/FAM-HUSB",
        "MARB": "https://gedcom.io/terms/v7/MARB",
        "MARC": "https://gedcom.io/terms/v7/MARC",
        "MARL": "https://gedcom.io/terms/v7/MARL",
        "MARR": "https://gedcom.io/terms/v7/MARR",
        "MARS": "https://gedcom.io/terms/v7/MARS",
        "NCHI": "https://gedcom.io/terms/v7/FAM-NCHI",
        "NO": "https://gedcom.io/terms/v7/NO",
        "NOTE": "https://gedcom.io/terms/v7/NOTE",
        "OBJE": "https://gedcom.io/terms/v7/OBJE",
        "REFN": "https://gedcom.io/terms/v7/REFN",
        "RESN": "https://gedcom.io/terms/v7/RESN",
        "RESI": "https://gedcom.io/terms/v7/FAM-RESI",
        "SLGS": "https://gedcom.io/terms/v7/SLGS",
        "SNOTE": "https://gedcom.io/terms/v7/SNOTE",
        "SOUR": "https://gedcom.io/terms/v7/SOUR",
        "SUBM": "https://gedcom.io/terms/v7/SUBM",
        "UID": "https://gedcom.io/terms/v7/UID",
        "WIFE": "https://gedcom.io/terms/v7/FAM-WIFE",
    },
    "https://gedcom.io/terms/v7/REPO": {
        "CALN": "https://gedcom.io/terms/v7/CALN",
        "NOTE": "https://gedcom.io/terms/v7/NOTE",
        "SNOTE": "https://gedcom.io/terms/v7/SNOTE",
    },
    "https://gedcom.io/terms/v7/record-OBJE": {
        "CHAN": "https://gedcom.io/terms/v7/CHAN",
        "CREA": "https://gedcom.io/terms/v7/CREA",
        "EXID": "https://gedcom.io/terms/v7/EXID",
        "FILE": "https://gedcom.io/terms/v7/FILE",
        "NOTE": "https://gedcom.io/terms/v7/NOTE",
        "REFN": "https://gedcom.io/terms/v7/REFN",
        "RESN": "https://gedcom.io/terms/v7/RESN",
        "SNOTE": "https://gedcom.io/terms/v7/SNOTE",
        "SOUR": "https://gedcom.io/terms/v7/SOUR",
        "UID": "https://gedcom.io/terms/v7/UID",
    },
    "https://gedcom.io/terms/v7/record-SNOTE": {
        "CHAN": "https://gedcom.io/terms/v7/CHAN",
        "CREA": "https://gedcom.io/terms/v7/CREA",
        "EXID": "https://gedcom.io/terms/v7/EXID",
        "LANG": "https://gedcom.io/terms/v7/LANG",
        "MIME": "https://gedcom.io/terms/v7/MIME",
        "REFN": "https://gedcom.io/terms/v7/REFN",
        "SOUR": "https://gedcom.io/terms/v7/SOUR",
        "TRAN": "https://gedcom.io/terms/v7/NOTE-TRAN",
        "UID": "https://gedcom.io/terms/v7/UID",
    },
    "HEAD pseudostructure": {
        "COPR": "https://gedcom.io/terms/v7/COPR",
        "DATE": "https://gedcom.io/terms/v7/HEAD-DATE",
        "DEST": "https://gedcom.io/terms/v7/DEST",
        "GEDC": "https://gedcom.io/terms/v7/GEDC",
        "LANG": "https://gedcom.io/terms/v7/HEAD-LANG",
        "NOTE": "https://gedcom.io/terms/v7/NOTE",
        "PLAC": "https://gedcom.io/terms/v7/HEAD-PLAC",
        "SCHMA": "https://gedcom.io/terms/v7/SCHMA",
        "SNOTE": "https://gedcom.io/terms/v7/SNOTE",
        "SOUR": "https://gedcom.io/terms/v7/HEAD-SOUR",
        "SUBM": "https://gedcom.io/terms/v7/SUBM",
    },
    "https://gedcom.io/terms/v7/HEAD-SOUR-DATA": {
        "COPR": "https://gedcom.io/terms/v7/COPR",
        "DATE": "https://gedcom.io/terms/v7/DATE-exact",
    },
    "https://gedcom.io/terms/v7/HEAD-SOUR": {
        "CORP": "https://gedcom.io/terms/v7/CORP",
        "DATA": "https://gedcom.io/terms/v7/HEAD-SOUR-DATA",
        "NAME": "https://gedcom.io/terms/v7/NAME",
        "VERS": "https://gedcom.io/terms/v7/VERS",
    },
    "https://gedcom.io/terms/v7/OBJE": {
        "CROP": "https://gedcom.io/terms/v7/CROP",
        "TITL": "https://gedcom.io/terms/v7/TITL",
    },
    "https://gedcom.io/terms/v7/SOUR": {
        "DATA": "https://gedcom.io/terms/v7/SOUR-DATA",
        "EVEN": "https://gedcom.io/terms/v7/SOUR-EVEN",
        "NOTE": "https://gedcom.io/terms/v7/NOTE",
        "OBJE": "https://gedcom.io/terms/v7/OBJE",
        "PAGE": "https://gedcom.io/terms/v7/PAGE",
        "QUAY": "https://gedcom.io/terms/v7/QUAY",
        "SNOTE": "https://gedcom.io/terms/v7/SNOTE",
    },
    "https://gedcom.io/terms/v7/BAPL": {
        "DATE": "https://gedcom.io/terms/v7/DATE",
        "NOTE": "https://gedcom.io/terms/v7/NOTE",
        "PLAC": "https://gedcom.io/terms/v7/PLAC",
        "SNOTE": "https://gedcom.io/terms/v7/SNOTE",
        "SOUR": "https://gedcom.io/terms/v7/SOUR",
        "STAT": "https://gedcom.io/terms/v7/ord-STAT",
        "TEMP": "https://gedcom.io/terms/v7/TEMP",
    },
    "https://gedcom.io/terms/v7/CONL": {
        "DATE": "https://gedcom.io/terms/v7/DATE",
        "NOTE": "https://gedcom.io/terms/v7/NOTE",
        "PLAC": "https://gedcom.io/terms/v7/PLAC",
        "SNOTE": "https://gedcom.io/terms/v7/SNOTE",
        "SOUR": "https://gedcom.io/terms/v7/SOUR",
        "STAT": "https://gedcom.io/terms/v7/ord-STAT",
        "TEMP": "https://gedcom.io/terms/v7/TEMP",
    },
    "https://gedcom.io/terms/v7/ENDL": {
        "DATE": "https://gedcom.io/terms/v7/DATE",
        "NOTE": "https://gedcom.io/terms/v7/NOTE",
        "PLAC": "https://gedcom.io/terms/v7/PLAC",
        "SNOTE": "https://gedcom.io/terms/v7/SNOTE",
        "SOUR": "https://gedcom.io/terms/v7/SOUR",
        "STAT": "https://gedcom.io/terms/v7/ord-STAT",
        "TEMP": "https://gedcom.io/terms/v7/TEMP",
    },
    "https://gedcom.io/terms/v7/INIL": {
        "DATE": "https://gedcom.io/terms/v7/DATE",
        "NOTE": "https://gedcom.io/terms/v7/NOTE",
        "PLAC": "https://gedcom.io/terms/v7/PLAC",
        "SNOTE": "https://gedcom.io/terms/v7/SNOTE",
        "SOUR": "https://gedcom.io/terms/v7/SOUR",
        "STAT": "https://gedcom.io/terms/v7/ord-STAT",
        "TEMP": "https://gedcom.io/terms/v7/TEMP",
    },
    "https://gedcom.io/terms/v7/SLGC": {
        "DATE": "https://gedcom.io/terms/v7/DATE",
        "FAMC": "https://gedcom.io/terms/v7/FAMC",
        "NOTE": "https://gedcom.io/terms/v7/NOTE",
        "PLAC": "https://gedcom.io/terms/v7/PLAC",
        "SNOTE": "https://gedcom.io/terms/v7/SNOTE",
        "SOUR": "https://gedcom.io/terms/v7/SOUR",
        "STAT": "https://gedcom.io/terms/v7/ord-STAT",
        "TEMP": "https://gedcom.io/terms/v7/TEMP",
    },
    "https://gedcom.io/terms/v7/SLGS": {
        "DATE": "https://gedcom.io/terms/v7/DATE",
        "NOTE": "https://gedcom.io/terms/v7/NOTE",
        "PLAC": "https://gedcom.io/terms/v7/PLAC",
        "SNOTE": "https://gedcom.io/terms/v7/SNOTE",
        "SOUR": "https://gedcom.io/terms/v7/SOUR",
        "STAT": "https://gedcom.io/terms/v7/ord-STAT",
        "TEMP": "https://gedcom.io/terms/v7/TEMP",
    },
    "https://gedcom.io/terms/v7/SOUR-DATA": {
        "DATE": "https://gedcom.io/terms/v7/DATE",
        "TEXT": "https://gedcom.io/terms/v7/TEXT",
    },
    "https://gedcom.io/terms/v7/CHAN": {
        "DATE": "https://gedcom.io/terms/v7/DATE-exact",
        "NOTE": "https://gedcom.io/terms/v7/NOTE",
        "SNOTE": "https://gedcom.io/terms/v7/SNOTE",
    },
    "https://gedcom.io/terms/v7/CREA": {
        "DATE": "https://gedcom.io/terms/v7/DATE-exact"
    },
    "https://gedcom.io/terms/v7/ord-STAT": {
        "DATE": "https://gedcom.io/terms/v7/DATE-exact"
    },
    "https://gedcom.io/terms/v7/NO": {
        "DATE": "https://gedcom.io/terms/v7/NO-DATE",
        "NOTE": "https://gedcom.io/terms/v7/NOTE",
        "SNOTE": "https://gedcom.io/terms/v7/SNOTE",
        "SOUR": "https://gedcom.io/terms/v7/SOUR",
    },
    "https://gedcom.io/terms/v7/DATA-EVEN": {
        "DATE": "https://gedcom.io/terms/v7/DATA-EVEN-DATE",
        "PLAC": "https://gedcom.io/terms/v7/PLAC",
    },
    "https://gedcom.io/terms/v7/PLAC": {
        "EXID": "https://gedcom.io/terms/v7/EXID",
        "FORM": "https://gedcom.io/terms/v7/PLAC-FORM",
        "LANG": "https://gedcom.io/terms/v7/LANG",
        "MAP": "https://gedcom.io/terms/v7/MAP",
        "NOTE": "https://gedcom.io/terms/v7/NOTE",
        "SNOTE": "https://gedcom.io/terms/v7/SNOTE",
        "TRAN": "https://gedcom.io/terms/v7/PLAC-TRAN",
    },
    "": {
        "FAM": "https://gedcom.io/terms/v7/record-FAM",
        "INDI": "https://gedcom.io/terms/v7/record-INDI",
        "OBJE": "https://gedcom.io/terms/v7/record-OBJE",
        "REPO": "https://gedcom.io/terms/v7/record-REPO",
        "SNOTE": "https://gedcom.io/terms/v7/record-SNOTE",
        "SOUR": "https://gedcom.io/terms/v7/record-SOUR",
        "SUBM": "https://gedcom.io/terms/v7/record-SUBM",
    },
    "https://gedcom.io/terms/v7/FILE": {
        "FORM": "https://gedcom.io/terms/v7/FORM",
        "TITL": "https://gedcom.io/terms/v7/TITL",
        "TRAN": "https://gedcom.io/terms/v7/FILE-TRAN",
    },
    "https://gedcom.io/terms/v7/FILE-TRAN": {"FORM": "https://gedcom.io/terms/v7/FORM"},
    "https://gedcom.io/terms/v7/HEAD-PLAC": {
        "FORM": "https://gedcom.io/terms/v7/HEAD-PLAC-FORM"
    },
    "https://gedcom.io/terms/v7/INDI-NAME": {
        "GIVN": "https://gedcom.io/terms/v7/GIVN",
        "NICK": "https://gedcom.io/terms/v7/NICK",
        "NOTE": "https://gedcom.io/terms/v7/NOTE",
        "NPFX": "https://gedcom.io/terms/v7/NPFX",
        "NSFX": "https://gedcom.io/terms/v7/NSFX",
        "SNOTE": "https://gedcom.io/terms/v7/SNOTE",
        "SOUR": "https://gedcom.io/terms/v7/SOUR",
        "SPFX": "https://gedcom.io/terms/v7/SPFX",
        "SURN": "https://gedcom.io/terms/v7/SURN",
        "TRAN": "https://gedcom.io/terms/v7/NAME-TRAN",
        "TYPE": "https://gedcom.io/terms/v7/NAME-TYPE",
    },
    "https://gedcom.io/terms/v7/NAME-TRAN": {
        "GIVN": "https://gedcom.io/terms/v7/GIVN",
        "LANG": "https://gedcom.io/terms/v7/LANG",
        "NICK": "https://gedcom.io/terms/v7/NICK",
        "NPFX": "https://gedcom.io/terms/v7/NPFX",
        "NSFX": "https://gedcom.io/terms/v7/NSFX",
        "SPFX": "https://gedcom.io/terms/v7/SPFX",
        "SURN": "https://gedcom.io/terms/v7/SURN",
    },
    "https://gedcom.io/terms/v7/CROP": {
        "HEIGHT": "https://gedcom.io/terms/v7/HEIGHT",
        "LEFT": "https://gedcom.io/terms/v7/LEFT",
        "TOP": "https://gedcom.io/terms/v7/TOP",
        "WIDTH": "https://gedcom.io/terms/v7/WIDTH",
    },
    "https://gedcom.io/terms/v7/NOTE": {
        "LANG": "https://gedcom.io/terms/v7/LANG",
        "MIME": "https://gedcom.io/terms/v7/MIME",
        "SOUR": "https://gedcom.io/terms/v7/SOUR",
        "TRAN": "https://gedcom.io/terms/v7/NOTE-TRAN",
    },
    "https://gedcom.io/terms/v7/NOTE-TRAN": {
        "LANG": "https://gedcom.io/terms/v7/LANG",
        "MIME": "https://gedcom.io/terms/v7/MIME",
    },
    "https://gedcom.io/terms/v7/PLAC-TRAN": {"LANG": "https://gedcom.io/terms/v7/LANG"},
    "https://gedcom.io/terms/v7/TEXT": {
        "LANG": "https://gedcom.io/terms/v7/LANG",
        "MIME": "https://gedcom.io/terms/v7/MIME",
    },
    "https://gedcom.io/terms/v7/MAP": {
        "LATI": "https://gedcom.io/terms/v7/LATI",
        "LONG": "https://gedcom.io/terms/v7/LONG",
    },
    "https://gedcom.io/terms/v7/CALN": {"MEDI": "https://gedcom.io/terms/v7/MEDI"},
    "https://gedcom.io/terms/v7/FORM": {"MEDI": "https://gedcom.io/terms/v7/MEDI"},
    "https://gedcom.io/terms/v7/ASSO": {
        "NOTE": "https://gedcom.io/terms/v7/NOTE",
        "PHRASE": "https://gedcom.io/terms/v7/PHRASE",
        "ROLE": "https://gedcom.io/terms/v7/ROLE",
        "SNOTE": "https://gedcom.io/terms/v7/SNOTE",
        "SOUR": "https://gedcom.io/terms/v7/SOUR",
    },
    "https://gedcom.io/terms/v7/FAMS": {
        "NOTE": "https://gedcom.io/terms/v7/NOTE",
        "SNOTE": "https://gedcom.io/terms/v7/SNOTE",
    },
    "https://gedcom.io/terms/v7/INDI-FAMC": {
        "NOTE": "https://gedcom.io/terms/v7/NOTE",
        "PEDI": "https://gedcom.io/terms/v7/PEDI",
        "SNOTE": "https://gedcom.io/terms/v7/SNOTE",
        "STAT": "https://gedcom.io/terms/v7/FAMC-STAT",
    },
    "https://gedcom.io/terms/v7/AGE": {"PHRASE": "https://gedcom.io/terms/v7/PHRASE"},
    "https://gedcom.io/terms/v7/ALIA": {"PHRASE": "https://gedcom.io/terms/v7/PHRASE"},
    "https://gedcom.io/terms/v7/CHIL": {"PHRASE": "https://gedcom.io/terms/v7/PHRASE"},
    "https://gedcom.io/terms/v7/DATA-EVEN-DATE": {
        "PHRASE": "https://gedcom.io/terms/v7/PHRASE"
    },
    "https://gedcom.io/terms/v7/DATE": {
        "PHRASE": "https://gedcom.io/terms/v7/PHRASE",
        "TIME": "https://gedcom.io/terms/v7/TIME",
    },
    "https://gedcom.io/terms/v7/FAM-HUSB": {
        "PHRASE": "https://gedcom.io/terms/v7/PHRASE"
    },
    "https://gedcom.io/terms/v7/FAM-WIFE": {
        "PHRASE": "https://gedcom.io/terms/v7/PHRASE"
    },
    "https://gedcom.io/terms/v7/FAMC-ADOP": {
        "PHRASE": "https://gedcom.io/terms/v7/PHRASE"
    },
    "https://gedcom.io/terms/v7/FAMC-STAT": {
        "PHRASE": "https://gedcom.io/terms/v7/PHRASE"
    },
    "https://gedcom.io/terms/v7/MEDI": {"PHRASE": "https://gedcom.io/terms/v7/PHRASE"},
    "https://gedcom.io/terms/v7/NAME-TYPE": {
        "PHRASE": "https://gedcom.io/terms/v7/PHRASE"
    },
    "https://gedcom.io/terms/v7/NO-DATE": {
        "PHRASE": "https://gedcom.io/terms/v7/PHRASE"
    },
    "https://gedcom.io/terms/v7/PEDI": {"PHRASE": "https://gedcom.io/terms/v7/PHRASE"},
    "https://gedcom.io/terms/v7/ROLE": {"PHRASE": "https://gedcom.io/terms/v7/PHRASE"},
    "https://gedcom.io/terms/v7/SDATE": {
        "PHRASE": "https://gedcom.io/terms/v7/PHRASE",
        "TIME": "https://gedcom.io/terms/v7/TIME",
    },
    "https://gedcom.io/terms/v7/SOUR-EVEN": {
        "PHRASE": "https://gedcom.io/terms/v7/PHRASE",
        "ROLE": "https://gedcom.io/terms/v7/ROLE",
    },
    "https://gedcom.io/terms/v7/SCHMA": {"TAG": "https://gedcom.io/terms/v7/TAG"},
    "https://gedcom.io/terms/v7/DATE-exact": {
        "TIME": "https://gedcom.io/terms/v7/TIME"
    },
    "https://gedcom.io/terms/v7/HEAD-DATE": {"TIME": "https://gedcom.io/terms/v7/TIME"},
    "https://gedcom.io/terms/v7/REFN": {"TYPE": "https://gedcom.io/terms/v7/TYPE"},
    "https://gedcom.io/terms/v7/EXID": {"TYPE": "https://gedcom.io/terms/v7/EXID-TYPE"},
    "https://gedcom.io/terms/v7/GEDC": {"VERS": "https://gedcom.io/terms/v7/GEDC-VERS"},
}
